### ISSUE TITLE
Translation

### ISSUE THREAD

**Issue by kveldhuis** [nhnent/tui.editor#10]
Hello,

Is it possible that we can get the language strings in an stand alone file in the project. So we can translate easily the editor?

**Comment by shiren** [comment]
Unfortunately, we don't have any file what you want currently. but we have plan to implement feature for Internationalization. when we have done this feature we will be close this issue. so you could do what you want soon. thanks

**Comment by shiren** [comment]
We have implemented this feature in 0.10.0
Check [Getting started](https://github.com/nhnent/tui.editor/wiki/Getting-Started)
