### ISSUE TITLE
wrong escaping in list

### ISSUE THREAD

**Issue by kyuwoo-choi** [nhnent/tui.editor#105]
## Version

1.0.4

## Test Environment

WYSIWYG

## Current Behavior

1. type below in WISYWIG mode
```
1. <payco beauty>
2. <123>
```

2. change to Markdown mode
```md
1. \<payco beauty>
2\. <123\>
```

## Expected Behavior

```md
1\. \<payco beauty>
2\. \<123>
```

**Comment by zzsataniczz** [comment]
UP
Hello! When this problem will be solved?

**Comment by sohee-lee7** [comment]
@zzsataniczz This issue resolved
