### ISSUE TITLE
Are all charts from tui-chart available ?

### ISSUE THREAD

**Issue by Yaty** [nhnent/tui.editor#115]
Hi !
Thanks for the tui ecosystem :)
I'm wondering if all charts from tui-chart are working on tui-editor and if it's not then is it planned ?
I love charts from tui-chart and I would love to be able to use them in tui-editor :)
Yaty,

**Comment by kyuwoo-choi** [comment]
Hey @Yaty I love to hear that you're interested in our chart 😄 

I'm afraid that the chart extension can't cover all type of the chart.
Currently, chart extension will do bar, column, line, area, pie types which the data can be represented in a simple table.

It will work with the other types after we discuss how to handle the chart data.

I'm closing it.
feel free to open it again, if you have further question or want to discuss this.
