### ISSUE TITLE
add an option for initial HTML text

### ISSUE THREAD

**Issue by alirizaadiyahsi** [nhnent/tui.editor#116]
Is there a way to convert already rendered value to editor value? I mean `initialValue` from rendered html. For example;

```html
<div id="markdownEditor">
    <span>rendered value</span>
</div>
```

```js
var markdownEditor = new tui.Editor({
        el: document.querySelector('#markdownEditor'),
        initialEditType: 'markdown',
        previewStyle: 'tab',
        height: '400px'
});
```

I expect an editor with initialValue `<span>rendered value</span>`. Is there a way to achive this?

**Comment by kyuwoo-choi** [comment]
It currently has no option for that.
We may add an option for the HTML text.

For now, as a workaround, you can use [setHtml()](http://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#setHtml) after the editor initialization.

I'm going to tag this **help wanted**
anyone interested in implement this, please go ahead and send me a PR.

**Comment by alirizaadiyahsi** [comment]
This is very important feature. For example think about github issues or stackoverflow question-answer flow. There need to be more than one viewer. And I expect that something like following;

**HTML**
```html
<div class="viewer">
    <span>some pre-rendered html</span>
    ...
</div>

...

<div class="viewer">
    <span>some another pre-rendered html</span>
    ...
</div>
```

JS
```js
$('.viewer').viewer();
```

**Comment by shandrolis** [comment]
What ever happened to this?

**Comment by sohee-lee7** [comment]
Adding an option for initial HTML text in Viewer is keep going in #360
