### ISSUE TITLE
Need PlaceHolder for the Editor

### ISSUE THREAD

**Issue by kishorethecoder** [nhnent/tui.editor#117]
It would be nice feature to have the Place Holder option in the Editor

**Comment by kyuwoo-choi** [comment]
I'll tag this **help wanted**
It won't require deep understanding the editor.

send me a PR if someone interested in it.

**Comment by miguelcobain** [comment]
@kyuwoo-choi could you give us some hints on how to implement this?

**Comment by Cygnus2112** [comment]
I also am interested in this.
