### ISSUE TITLE
Codeblock doesn't work with other themes than github.css

### ISSUE THREAD

**Issue by tormodvm** [nhnent/tui.editor#120]
## Version
1.0.5

## Test Environment
Chrome 64 on MacOS 10.12.6

## Current Behavior
If I include a different theme than github.css, i.e. Monokai, it doesn't work correctly. It seems some css values in the codeblock is hardcoded in, and not fetched from the theme.

See [this flems.io](https://flems.io/#0=N4IgtglgJlA2CmIBcBmATAOjQFgDQgDMIEBnZAbVADsBDMRJEDACwBcxYR8BjAeytbwByEAB4oEAG4ACaAF4AOiHgTWAZXjdWEfkoB8ogPQTJehVRABfXNToMmAKzI9+g4Y0k0ATtL4ChrNJy0uTm0uHSAOQABrEONJ4k3F4QAA6skbhhEZEAJAAUSgDEKhDqmtq6IACUGKwArhAAoqq8XvnAmdnhkRBUZRA0sC1lACoAnqnwSNJKYN4A1lC8AO5USrhdVBFRqV7wkhDwK2qs4wgzSpLwXtrcQxtbO5HM8BAA5myXICgADL+pAAejyy2xylmqAG4njlYtEYT0EVE4WwOEjIuIpHpRvASKwjCY9Oi4ZFutIALoYBy8Pr5UnmSJQ8zmArFUrlLQ6dY1OqNEasNodMl9AZDfkTKbfeZeJarbmgnZ7A5HE5nC6zEDXW4Qe6wDZk14fL4av4A4FcYX9bRDABqQ3q018rgC2QhkKsNhAtHoIgw3BIzhAfjcrBEqNg0mA2QARrxAQBaEgQABefXeM1jXigN3jscBkPMlnMACpcNJi0ho-ACG14GWKzQCIIfFGwXnEym0zM+q8UqwC1Qi+sqOHcLGoONI9lDZ9WDMAIz-ACkA-C0vefRmv1X0lSNBgXek28LzKoJVUGk5-CnYJnxsXvyX0gAhBAwKk2qwaAIB5YrOT8FgPoFjIJBKC9OwRAcABHB0vHGKlA3qLxOEYNhWFSEgkEMQx6ioVIFneP1eDAQwYLg8YAAEUAwGj52MCA8TI2CbgQpwuBAM4pigshrFsH1GGlWU1njMpEI45DUJAdDMOw3D8MI4jSKE5YRLKSiAA4MGwDB6IkJiVLlUTWHE-AuPsdi+IggTON4eMhIklCw1YDCsJwvCCKIvhSIFezFko+ddIwX4GKY3yhNMzjJgs3jPW9ewGggeM+GzRN+lSKYTPY-BJOc1y5I8xTvMMRLkt4VKSHSzKAqwDAAE5QtYErGjKiqqvgLLA3MniPX4+wUvgSAvC8NpItytCXNk9yFK8kjDAGoaRq8SiAFZaLWkKgOjebysGiBhtG7Kou4xhLLiyC0KNIDZwwPduAWManIm-Lps8pTDGYK6jVYJxKLq3TfmCj6vpuu6HqO7rTtivqRBIWD9vgeMvBoFZHqkmS3Pkt7irhxp9iRwQaq0+c0EMaNGlgKBDFxhGkZRyLIZAM6YcYUr2TaeN+UOpCnukybMcK2afJa9nlsCwGVsa5qktFznWi8Bnop6qz4pEBb9qWv0A0c9H+YKmb3vVg7lrWlANsMLaduzRbRv9LqlcYO3eushKRflrWed1l6saKua2flmqJal-2ylt7WzIdoNtZVi7OLd0OvDK-wBBID2dbyqafaF6X41FwOMEl-SmpDgVE+DAJU6diOTqj6GXZEMB+F4BYaAgNOct5jH9exubPs+a62F+-7FyBvFzlxQxG6oZvW-b47+uj8lLCAA) for a demo. Here I've included the monokai.css theme instead of github.css, and it doesn't look right. Most noticeable is the light grey background instead of the dark.

## Expected Behavior
The expected behaviour would be to fetch all the codeblock styling from the theme.

Off-topic: Great project 😃 I really enjoy using it.

**Comment by kyuwoo-choi** [comment]
@TeddyBones 
Thanks for reporting it. and the example. it really helps 😃 

We override/rule out some code block styles to match with other UI.
I think I can remove the overriding rules and make a customized highlight.js theme for us.
Then you can see the theme works perfectly.

**Comment by sohee-lee7** [comment]
This is resolved so I will close it.
