### ISSUE TITLE
English expression improvement suggestion

### ISSUE THREAD

**Issue by jjangga0214** [nhnent/tui.editor#131]
In my opinion, several sentences on issue guide look a bit awkward.
The upper ones are the originals. The followings, my suggestions.

> When it comes to write an issue, please, use the template below.  
> When writing an issue, please, use the template below.

> To use the template is mandatory for submit new issue
> It's mandatory to use the template for submitting the new issue.

> we won't reply the issue that without the template.
> we dont't reply to the issue not following the template.

> Write a description of the detailed step to reproduce the current behavior
> Write steps to reproduce the current behavior in detail.

> Write a description of the future action.
> Write a description for future action.

**Comment by kyuwoo-choi** [comment]
would you send me a PR for it if you want?
Thank you @jjangga0214  😄
