### ISSUE TITLE
How to disable "Insert image"

### ISSUE THREAD

**Issue by medokin** [nhnent/tui.editor#135]
Are there any options to customize the toolbar?

**Comment by kyuwoo-choi** [comment]
It's coming soon. ETA 4/17
https://github.com/nhnent/tui.editor/milestone/3

**Comment by kyuwoo-choi** [comment]
resolved in https://github.com/nhnent/tui.editor/commit/cae38ea04fcacaba65d19e00f95684c0144de933

I don't have a tutorial for it at this moment.
You can refer to PR I made for an example: https://github.com/nhnent/tui.editor/pull/124

**Comment by kyuwoo-choi** [comment]
Btw. please wait for the tutorial if you can't do what you want along with the PR description.
