### ISSUE TITLE
This regex may be stucked by input

### ISSUE THREAD

**Issue by 2bdenny** [nhnent/tui.editor#141]
https://github.com/nhnent/tui.editor/blob/5a447c84e9acd6e5c1bd370d3ccf4c80dfe7b34f/src/js/markdownCommands/strike.js#L7
https://github.com/nhnent/tui.editor/blob/5a447c84e9acd6e5c1bd370d3ccf4c80dfe7b34f/src/js/markdownCommands/strike.js#L55

Hello =), I have tested all regexes in the project, and find this regex may be stucked by input. For example, the following code would cost over 30 seconds.
```
var testInput = "~&aF~&aF~&aF~&aF~&aF~&aF~&aFxDHD#";
hasStrikeSyntax(testInput);
```

**Comment by kyuwoo-choi** [comment]
LOL great 🤣 

Then it should be fixed. It could be used in DOS attack.

Thank you for your persistent test 💯

**Comment by kyuwoo-choi** [comment]
Hey @2bdenny 
btw, from the other issues you posted, I heard you made a tool for it.
great job. tell me when you publish that. I'll give a star. 😃

**Comment by Lemonstars** [comment]
@kyuwoo-choi https://2bdenny.github.io/ReScue/ This is the tool.

**Comment by sohee-lee7** [comment]
This issue does not occur in the latest version so close this issue.
