### ISSUE TITLE
BOLD is not working in the Toolbar

### ISSUE THREAD

**Issue by kishorethecoder** [nhnent/tui.editor#143]
## Version

1.1.0-a
## Test Environment

All Browser
## Current Behavior

Bold Button is not working on the toolbar.In the toolbarItemFactory.js the bold command is mismatched.
https://github.com/nhnent/tui.editor/blob/aba9f7d99eed13e03c880322a68a0478671ee538/src/js/ui/toolbarItemFactory.js#L40

## Expected Behavior

The Command should be **Bold**

**Comment by kyuwoo-choi** [comment]
Holy!
