### ISSUE TITLE
Support resize editor height with text length.

### ISSUE THREAD

**Issue by sagnol** [nhnent/tui.editor#149]
## Version
1.0.4

## Test Environment
Chrome, Mac OSX, (React)

## Current Behavior

Regardless of text length, it is a fixed height.

```js
// no code
```

## Expected Behavior

Resize editor height with text length or Add resize bar on editor bottom.

**Comment by kyuwoo-choi** [comment]
you can set `auto` to `option.height`

consider also setting `minHeight` option if you want.

http://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html
