### ISSUE TITLE
Publish to npm

### ISSUE THREAD

**Issue by tirli** [nhnent/tui.editor#15]
Hi. 
Do you have in plan to publish your package to npm? bower is a little outdated for now and It would be great if I can get it from npm as all other packages.

**Comment by kyuwoo-choi** [comment]
Hey @tirli 

We are preparing to release 1.0 and plan to register on npm starting in 1.0.
Before the release, there are a few things to be done to make it a npm module, in addition to some features and bug fixes. At that time, you can use tui.editor with tools you want like webpack, rollup and so on.

Thank you for your interest in tui.editor.

**Comment by zerosoup** [comment]
Hi - Just to say I just found this package and I had the same question. This is far and away the best WYSIWYG MD editor I have found so please let us know when it's available on npm.

**Comment by kyuwoo-choi** [comment]
Thanks for the compliment. @zerosoup 

The next release is the 1.0.(tada~~) And then it will be registered at npm. I can not give you the exact schedule, but it's not too far away so please wait patiently :)
And you know you'll have the notice if you star our project. Of course if I don't forget, I'll mention here too.

See ya!

**Comment by kyuwoo-choi** [comment]
Hey guys. now it on the npm 🎉
https://www.npmjs.com/package/tui-editor

**Comment by zerosoup** [comment]
Awesome! Thanks for the update.
