### ISSUE TITLE
Tui editor table popup selector box not aligning with the toolbar table button 

### ISSUE THREAD

**Issue by chas2015** [nhnent/tui.editor#151]
## Version 

version 1.0.6

## Test Environment

Windows 10 on Chrome

## Current Behavior

1. Place the tui editor on a page that the page is large enough to scroll vertically. 
2. Scroll down from the top of the page so the scroll bar is not all the way up.
3. Click on the table button on the toolbar. 

The popup table selector box is not aligning with the toolbar button. Depend on how big the page is, the popup table selector may even go out of view.

## Expected Behavior

The popup table selector should always align with the toolbar table button.

**Comment by chas2015** [comment]
The table selector popup also has selection issue. I can only select up to 2 rows and the column selection is not working properly either.

**Comment by galvarez421** [comment]
As of 1.1.1, I am still experiencing incorrect positioning for the headings dropdown/popup.

As described in the OP, the issue appears to occur when the page is scrolled down (see images below).

After clicking headings button when page is scrolled to top:

![scrolled-to-top](https://user-images.githubusercontent.com/12755056/40077343-628a2d22-584f-11e8-8cfd-8e9a4b69ce1a.PNG)

After clicking headings button when page is scrolled down:

![scrolled-down](https://user-images.githubusercontent.com/12755056/40077348-687bb2a0-584f-11e8-91ad-6d33d4d8b277.PNG)

**Comment by kyuwoo-choi** [comment]
Currently, popups are `fixed` position.

option 1
- dismiss popups on scrolling

option 2
- popups `absolute` position `relative` to toolbar element.

**Comment by vpapadopou** [comment]
FYI This problem also occurs when placing the editor inside a bootstrap modal.

One good idea would be to check how bootstrap does it in terms of css and html code. It creates a "button group" div that includes the button along with the dropdown. That way the dropdown cannot be placed far away from the button.
https://getbootstrap.com/docs/4.0/components/dropdowns/
