### ISSUE TITLE
popups through dropdown toolbar are misplaced

### ISSUE THREAD

**Issue by kyuwoo-choi** [nhnent/tui.editor#155]
## Version

1.1.0

## Test Environment

all

## Current Behavior

1. shrink width and see the '...' button on toolbar
2. click '...' button and see the dropdown toolbar
3. click 'table' button and see that table popup is misplaced

![image](https://user-images.githubusercontent.com/1215767/39108791-f882e2a8-4704-11e8-925f-aeeba8255554.png)

![image](https://user-images.githubusercontent.com/1215767/39108781-f07167e2-4704-11e8-9509-02819b5d3b9d.png)

## Expected Behavior

the table popup should be placed under the table button.
I guess heading & color button are affected this issue too.

**Comment by vpapadopou** [comment]
I've added a proposed solution in #151 that could also work for this case. In general, using the jquery to calculate and set fixed position for an item is not considered correct.

**Comment by kyuwoo-choi** [comment]
@vpapadopou

I've seen the issue and It's a different one since 1.1.0

I'll check the issue again.
meanwhile, thanks for the solution. that'll help ppl to workaround.

**Comment by kyuwoo-choi** [comment]
Currently, popups are `fixed` position.

option 1
- dismiss popups on scrolling

option 2
- popups `absolute` position `relative` to toolbar element.

**Comment by kyuwoo-choi** [comment]
dedup #151
