### ISSUE TITLE
youtube 동영상 링크를 이용해서 embedded 화면이 만들어 졌으면 좋겠습니다.

### ISSUE THREAD

**Issue by zbum** [nhnent/tui.editor#16]

**Comment by cybaek** [comment]
dooray에는 이 기능이 들어가 있어요. @kyuwoo-choi 
호우와 상의해서 기본으로 넣어도 되지 않을까요?

**Comment by kyuwoo-choi** [comment]
https://github.com/nhnent/tui.editor/blob/production/docs/writing-your-own-extension.md
https://nhnent.github.io/tui.editor/api/latest/tutorial-example12-writing-extension.html

요것들 참조해서 @Vnthf 가 만들어 줄거예요 :)

**Comment by kyuwoo-choi** [comment]
호우에게 맞기고 일단 닫아두겠습니다 :)

**Comment by kyuwoo-choi** [comment]
타이틀 제목을 제가 수정했습니다. 😢
외국인들도 같이 쓰는 만큼 이슈 관련되서 커밋이 올라갈때 적어도 추측은 할 수 있도록 하려합니다.
