### ISSUE TITLE
Cannot set Image size

### ISSUE THREAD

**Issue by cs09g** [nhnent/tui.editor#160]
## Version

The one which is used in `Dooray`

## Test Environment

Windows 7, Firefox

## Current Behavior

There's no way to set size of image.

## Expected Behavior

There should be a way to set image size. anyway with CSS like `![image](url){width: 200px; height: 100px}` or other syntax something like `![image](url =100x100)`

**Comment by kyuwoo-choi** [comment]
Thanks for the contribution @cs09g 

I see the syntax `![caption](url){attribute}` is not a commonmark syntax *yet*.
And It seems like the syntax is a matter of extensions.
- https://talk.commonmark.org/t/consistent-attribute-syntax/272/16
- https://talk.commonmark.org/t/generic-directives-plugins-syntax/444/147

I think they're going to merge the syntax, after all. It's not a subject for now.
So please wait for it happens :)

**Comment by cs09g** [comment]
so, tui.editor's markdown functionalities are from `markdown-it` which supports commonmark?
I thought tui.editor itself created markdown parser. then I'd better wait for their work done :)

**Comment by kyuwoo-choi** [comment]
yup! I'm closing this issue.
We'll consider the syntax when the spec has it.
