### ISSUE TITLE
Way to customize the insert image button behavior

### ISSUE THREAD

**Issue by inspiredjw** [nhnent/tui.editor#161]
Current toast editor use base64 image blob when an image is inserted with the image button in the toolbar.

Is there a way to call a custom callback function for the image button that uploads the image blob to my server and give back a real url of the uploaded image instead of the huge base64 image blob?

**Comment by kyuwoo-choi** [comment]
sure. that's a common use case for images.

- https://github.com/nhnent/tui.editor/issues/57
- https://github.com/nhnent/tui.editor/issues/127

**Comment by cavo789** [comment]
Thank you, I had the same question.
