### ISSUE TITLE
Bullet and Number list not working as expected

### ISSUE THREAD

**Issue by chas2015** [nhnent/tui.editor#166]
## Version

version 1.1.0

## Test Environment

IE on Windows 10

## Current Behavior

After selecting the bullet or number list from the toolbar, sometime the bullet list or number list does not work as expected. 

- Sometime, can not type anything after the bullet or number.
- Sometime, double enter to end the bullet list or number list does not work. It keeps on adding additional bullets or number.

## Expected Behavior

- The user should be able to consistently type what they want to after the bullet or number when using the bullet or number list. 
- The user should be able to consistently end the list with double enter (newline twice)

**Comment by kyuwoo-choi** [comment]
@chas2015 
can you provide the step so I can reproduce?

**Comment by chas2015** [comment]
Reproduce the issue of not being able to type after the bullet or number:

1. Use an IE browser and go to https://nhnent.github.io/tui.editor/api/latest/tutorial-example01-basic.html.
2. Select the WYSIWYG mode.
3. Click on the bullet button on the toolbar.
4. Don’t click any where in the editor and try to type something after the first bullet point.
5. Defect: No input is being accepted at this point.

Reproducing the issue of not being able to end the bullet or number list:

6. Continue from above, use the mouse to left click on the cursor and now the editor will be able to accept inputs.
7. Type a word, maybe ‘item’ and hit the enter key once .
8. Hit the enter key again.
9. Defect: The bullet list did not end after the second enter key was entered.

**Comment by sohee-lee7** [comment]
@chas2015 I'm sorry for the late replay. I try to reproduce this issue using v1.3.1 but it does not reproduce. I recommend to use the latest version. If this issue still occurs your environment, please give me another information.

**Comment by sohee-lee7** [comment]
@chas2015 This issue is so old so close it. If you have problem, please make a new issue.
