### ISSUE TITLE
Copy and right click issue in IE

### ISSUE THREAD

**Issue by chas2015** [nhnent/tui.editor#168]
## Version

version 1.1.0

## Test Environment

IE in Windows 10

## Current Behavior

Sometime, when I right click in the editor on a selected text, the text gets deleted or removed from the editor content. If the text does not disappear and I do get to the context menu then by copying the text will also cause the text to disappear.

## Expected Behavior

The selected text in editor  content should not disappear when being right click on or using the context menu to copy it.

**Comment by sohee-lee7** [comment]
@chas2015 I'm sorry for late reply. When I use the latest version, this issue does not happen. Please use the latest version. This issue is old so close it. If you have still problem, reopen or make a new issue.
