### ISSUE TITLE
Pb with tui and vuejs

### ISSUE THREAD

**Issue by ppaysant** [nhnent/tui.editor#17]
Hi,

I'm testing tui and it's seems pretty good. thx for releasing it :)
I have problem with loading underscorejs and tui.editor. Without underscorejs, tui.editor works fine,  but with underscorejs loaded, the editor displays but does not react (unable to write, click on any button, ...).
I tried to replace underscorejs with lodash without success.

tui.editor 0.14.0 (and its dependencies loaded by bower)
jquery 2.2.4
underscorejs 1.8.3
Tested on gnu/linux debian with firefox 52 and chrome 60

Any hint ?

**Comment by ppaysant** [comment]
Hmm... some more tests seems to show vuejs / tuieditor as the problem instead of undescorejs / tuieditor. Anyway, I can't use tui inside my application for now, and will hear any advice with joy !

**Comment by kyuwoo-choi** [comment]
I'll try reproduce the problem. meanwhile any detail will be welcomed

**Comment by ppaysant** [comment]
Thank you for your answer, @kyuwoo-choi !

Here are some code extracted from my app : 

The template (php / twig) part which will contain the editor (#editorZone).
```php
            <div class="box-body">
                <div id="editorVue" data-id="{{ pageId }}" v-cloak>
                    <label>Titre</label>
                    <div class="form-group">
                        <input class="form-control" :value="title" @input="update">
                    </div>

                    <label>Contenu</label>
                    <div class="form-group" id="editorZone">
                    </div>
                </div>
            </div>
```

The div "#editorVue" is my root vuejs instance.

The loaded js (yes, I'm not using webpack, nor any bundler :) ). The `<script>` markups are written just before `</body>`.
```html
<script src="/js/libs/jquery-2.2.4.min.js"></script>
<script src="/js/libs/bootstrap.min.js"></script>
<script src="/js/libs/vue.js"></script>

<script src="/js/libs/tui/lib/tui-code-snippet.js"></script>
<script src="/js/libs/tui/lib/markdown-it.js"></script>
<script src="/js/libs/tui/lib/toMark.js"></script>
<script src="/js/libs/tui/lib/codemirror.js"></script>
<script src="/js/libs/tui/lib/highlight.pack.js"></script>
<script src="/js/libs/tui/lib/squire-raw.js"></script>
<script src="/js/libs/tui/tui-editor.js"></script>

<script>
    $('#editorZone').tuiEditor({
        initialEditType: 'markdown',
        previewStyle: 'tab',
        height: '300px'
    })
    .tuiEditor('setValue', '# Hello');
</script>

<script src="/js/libs/underscore-min.js"></script>
<script src="/js/editor.js"></script>
```

editor.js is a (very simple) custom script that manages my vues js instance.
If I comment vuejs and editor.js, tui-editor is ok, else tui displays but does not react. 
Commenting only vuejs is also ok for tui, but with errors (shown in console) as editor.js needs it. (That lets me think editor.js is not the problem).

If you need specific information, please do not hesitate to ask. I will give them happily :)

**Comment by sebastiaanluca** [comment]
Unable to use it here to. WYSIWYG editor works somewhat fine, but cursor doesn't show in Markdown view and scrolling doesn't work. Typing inserts data at random positions, not very consistent.

**Comment by sohee-lee7** [comment]
@ppaysant 
Sorry for the late reply. We release vue wrapper for tui.editor. https://github.com/nhnent/toast-ui.vue-editor
Please use this wrapper. If there is some problem when using vue wrapper, leave issue in the vue wrapper of tui.editor.
I will close this issue.
