### ISSUE TITLE
img with onload attribute may cause xss problem.

### ISSUE THREAD

**Issue by LiangCY** [nhnent/tui.editor#172]
## Version
1.1.0

## Test Environment
Chrome

## Current Behavior

onload is filtered out, but 'xss' still alert.
```html
<img src="/image.jpg" onload="alert('xss')"/>
```

**Comment by sohee-lee7** [comment]
@LiangCY For using the latest version, this issue does not occur so I will close this issue. If you have problem, please reopen or make a new issue.
