### ISSUE TITLE
How to add toolbar items?

### ISSUE THREAD

**Issue by SteveSchreiner** [nhnent/tui.editor#174]
Do you have an example of how to add toolbarItems?

http://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html

**Comment by Ray-Eldath** [comment]
Same question...

**Comment by Prasad259** [comment]
Please add some example to add toolbarItems.

**Comment by 1c7** [comment]
same

**Comment by 1c7** [comment]
Hey guys, I just found few example

## Example 1:
https://github.com/nhnent/tui.editor/pull/124

## Example 2:
```
this.editor.exec('Bold')
```
https://github.com/nhnent/tui.editor/issues/240
http://nhnent.github.io/tui.editor/api/latest/CommandManager.html

**Comment by Ray-Eldath** [comment]
Certainly helps! Many thanks! 😄  @1c7

**Comment by kyuwoo-choi** [comment]
Thanks @1c7 
Look good to close this issue now.
