### ISSUE TITLE
google analytics collect issue

### ISSUE THREAD

**Issue by SteveSchreiner** [nhnent/tui.editor#175]
How do I disable these from being called? I tried usageStatistics: false but that made no difference.

  _tuiCodeSnippet2.default.imagePing('https://www.google-analytics.com/collect', {
    v: 1,
    t: hitType,
    tid: trackingID,
    cid: hostname,
    dp: hostname,
    dh: applicationID
  });

This is the error I see is form tui-color-picker

Refused to load the image 'https://www.google-analytics.com/collect?v=1&t=event&tid=UA-115377265-9&cid=localhost&dp=localhost&dh=color-picker' because it violates the following Content Security Policy directive: "img-src 'self' data:".

**Comment by kyuwoo-choi** [comment]
Well. you sure `useageStatistics = false`?

setting the option should prevent calling the function.

https://github.com/nhnent/tui.editor/blob/master/src/js/editor.js#L214

**Comment by SteveSchreiner** [comment]
It actually inside of tui-color-picker.js where you are setting usageStatistics: true (around line 2044)

`	function ColorPicker(options) {
	    var layout;

	    if (!(this instanceof ColorPicker)) {
	        return new ColorPicker(options);
	    }
	    /**
	     * Option object
	     * @type {object}
	     * @private
	     */
	    options = this.options = util.extend({
	        container: null,
	        color: '#f8f8f8',
	        preset: ['#181818', '#282828', '#383838', '#585858', '#b8b8b8', '#d8d8d8', '#e8e8e8', '#f8f8f8', '#ab4642', '#dc9656', '#f7ca88', '#a1b56c', '#86c1b9', '#7cafc2', '#ba8baf', '#a16946'],
	        cssPrefix: 'tui-colorpicker-',
	        detailTxt: 'Detail',
	        usageStatistics: true <== set to true
	    }, options);
`

**Comment by kyuwoo-choi** [comment]
oh. I'll fix this soon.
