### ISSUE TITLE
Retina (@2x) icons

### ISSUE THREAD

**Issue by jackmcdade** [nhnent/tui.editor#18]
It would be great if Retina/High-resolution icons were built in natively.

**Comment by kyuwoo-choi** [comment]
We do not plan to do that yet, but we will consider it later.

**Comment by cybaek** [comment]
@kyuwoo-choi , we have discussed the custom markdown grammar to display the retina image properly. It would be nice to start the talk again.

**Comment by kyuwoo-choi** [comment]
@cybaek I think @jackmcdade  is asking retina icons on toolbar buttons.
btw. sure we can talk retina image on content area on the other thread.

**Comment by bora89** [comment]
Yes, guys with no retina icons the editor looks ugly (toolbar icons). Ideally it should be SVGs or another kind of vector graphics. What we can do to move it further?
