### ISSUE TITLE
How to hide the URL tab within the insert image window?

### ISSUE THREAD

**Issue by SteveSchreiner** [nhnent/tui.editor#183]
How can I hide the URL tab in the insert image window?

![hide-url-tab](https://user-images.githubusercontent.com/1679643/40129237-c945b5ec-5901-11e8-82c6-d6f553222deb.png)

**Comment by SteveSchreiner** [comment]
I found in the source code where the URL tab is being added and was able to remove it successfully.  It would be really nice to be able to specify editor option to hide URL image tab, such as hideImageURLTab: true

**Comment by mark71692** [comment]
hello is the option to hide specific tabs on the image toolbar implemented?
