### ISSUE TITLE
Option to initially show markdown preview

### ISSUE THREAD

**Issue by SteveSchreiner** [nhnent/tui.editor#184]
## Current Behavior
When the editor is in markdown mode, the "Write" tab is initially the active tab.  I would like to specify an editor option to have the "Preview" tab to be the initially active tab.  Ths can be accomplished in the code below using a new showMarkdownPreview option.

```js
    key: '_markdownTabControl',
    value: function _markdownTabControl() {
      if (this._editor.isMarkdownMode() && this._editor.getCurrentPreviewStyle() === 'tab') {
        this._$markdownTabSection.show();
        this._markdownTab.activate(this._editor.options.showMarkdownPreview ? _i18n2.default.get('Preview') : _i18n2.default.get('Write'));
      } else {
        this._$markdownTabSection.hide();
      }
    }
```

**Comment by kyuwoo-choi** [comment]
@SteveSchreiner Nice.
I think you can use your implementation as it is now.
Send us a PR if you like.

Thank you.

**Comment by wolfmanx** [comment]
This does not work fully as expected. The toolbar buttons will not be disabled.

Clicking the *preview* button programmatically, does it correctly:

    $editor.find('.te-markdown-tab-section button[data-index="' + 1 + '"]').click()

**Comment by sohee-lee7** [comment]
This issue is old so I will close it.
