### ISSUE TITLE
Writing Regular font with iItalics without space

### ISSUE THREAD

**Issue by sandy9git** [nhnent/tui.editor#185]
## Version
1.1.1

## Test Environment
Mac 10.13.4, Chrome 66.0

## Current Behavior
Open http://nhnent.github.io/tui.editor/api/latest/tutorial-example01-basic.html
Type a_bc_ it outputs as a_bc_ instead it should be a*bc* 

Bold works fine a**bc**

## Expected Behavior
It should show bc in italics

**Comment by chocochaos** [comment]
Perhaps this is related: when setting the editor contents in WYSIWYG mode using setMarkdown, italics is not parsed correctly either, while bold works fine.

**Comment by kyuwoo-choi** [comment]
It's a correct behavior according to commonmark spec.
You should do `a*bc*` instead of `a_bc_`.

https://spec.commonmark.org/0.28/#example-340

**Comment by sandy9git** [comment]
thanks for the clarification @kyuwoo-choi , when selecting italics in WYSIWYG mode it adds _ it would be better if it adds * instead. Or is there a way we can override what gets added when we click on italics button

**Comment by kyuwoo-choi** [comment]
@sandy9git good point. sorry I skipped your previous comment.

In that case of converter behavior, We should consider changing the italic to `*` from `_`.
Before we jump right in, Let us investigate the effects what the change will bring in.
If no problem, we'll change it.

ps.
Recently, I've added a customizable toolbar feature. You can override toolbar buttons.
But we should fix the converter too.

**Comment by sandy9git** [comment]
Awesome! thanks @kyuwoo-choi

**Comment by sohee-lee7** [comment]
This issue is continue #409
