### ISSUE TITLE
tui.editor 2개 일때 이미지 안보이는 현상.

### ISSUE THREAD

**Issue by globeer** [nhnent/tui.editor#19]
tui.editor를 이용하여 QnA 게시판을 만들었습니다.

왼쪽에 질의사항을 보이고 오른쪽에 답변사항을 편집하는데,

답변사항에서 이미지 붙여넣기한 후에 저장하고,

다시 열면 이미지가 byte 문자열로 보입니다.

확인 부탁드립니다.

**Comment by kyuwoo-choi** [comment]
안녕하세요.

이미지 붙여넣기 할때와 다시 열었을때 에디터가 다르지 않은지 확인해보세요.

붙여넣기 한 이미지는
마크다운 에디터에서 base64 인코드된 마크다운 문법,
viewOnly 모드에서 이미지 랜더링,
마크다운 미리보기에서 이미지 랜더링,
위지윅 에디터에서 이미지 랜더링 하여 보여주고 있습니다.

**Comment by kyuwoo-choi** [comment]
타이틀 제목을 제가 수정했습니다. 😢
외국인들도 같이 쓰는 만큼 이슈 관련되서 커밋이 올라갈때 적어도 추측은 할 수 있도록 하려합니다.
