### ISSUE TITLE
How to create custom rendering for certain tags?

### ISSUE THREAD

**Issue by laurent22** [nhnent/tui.editor#199]
## Version

1.2.2

## Test Environment

Electron

In my application I can have links like this: `![](:/2c3b27cb3b7e49ea881c8218d965d0ce)` where `:/2c3...` refers to an image internal to the application.

So I need a way, when the renderer reaches this tag, to load the image and display it in the viewer.

With marked.js it would look something like this for example:

```
renderer.image = function (href, title) {
	const imageBase64 = loadImageAsBase64(href);
	return '<img src="' + imageBase64 + '"/>';
};
```

I've checked the TUI doc but couldn't find how to do this. Is it current possible and, if so, how?

**Comment by sohee-lee7** [comment]
@laurent22 I'm sorry for late reply. There is hook for adding image. That is [addImageBlobHook](http://nhnent.github.io/tui.editor/api/latest/global.html#addImageBlobHook). This event is like the event you were looking for. Callback of `addImageBlobHook` as parameter could be received url so pass the replaced url.

**Comment by sohee-lee7** [comment]
@laurent22 This issue is old so I will close it. If you have still problem using image, please reopen this issue or make a new issue.
