### ISSUE TITLE
Question : put the toolbar on two lines, is it possible ? 

### ISSUE THREAD

**Issue by cavo789** [nhnent/tui.editor#224]
Hi all,

Is there a configuration option for putting the toolbar on two lines ? 

The "..." (more) button is already a great feature but, yes, I'll prefer to have two lines 
(with orange background, my added buttons and I'll perhaps add more in the future)

![2018-06-22_12h45_30](https://user-images.githubusercontent.com/355999/41772756-2fe6916a-761a-11e8-8ca0-9b2fd8c796af.png)

Thanks !

**Comment by sohee-lee7** [comment]
@cavo789 Sorry for late reply. Currently not support two line toolbar. If you customize toolbar, maybe two line would be possible. This issue is old so I close it. If you have any problem, please make a new issue.
