### ISSUE TITLE
Feature : rename viewer

### ISSUE THREAD

**Issue by Fl0ux** [nhnent/tui.editor#228]
The idea is to rename the viewer so we could instantiate both the editor and the viewer on the same page.

Example : 
`var editor = new tui.Editor();`
`var viewer = new tui.Viewer();`

**Comment by kyuwoo-choi** [comment]
You can retrieve the viewer from the 'Editor.js', 'Editor-all.js'

try below
```js
tui.Editor.factory({
  ... // any other options you need
  viewer: true
});
```

It'll instantiate a new viewer. 😄
