### ISSUE TITLE
Enabling UML Extension in Viewer crashes TUI Editor

### ISSUE THREAD

**Issue by writepubapp** [nhnent/tui.editor#229]
## Version
v1.2.3

## Test Environment
Windows, Linux, Mac. [Chrome, Firefox] 

## Current Behavior
Viewer crash/error if uml extension enabled

## Source code
Identical to: http://nhnent.github.io/tui.editor/api/latest/tutorial-example10-viewer-multiple-extensions.html
This example uses Viewer & UML extension

## Expected Behavior

1. UML Extension enabled in viewer should not cause an error
2. To avoid this in the future, please add the above mentioned example to the CI/CD pipelines and unit tests

**Comment by writepubapp** [comment]
Hello @kyuwoo-choi This bug is blocking the use of UML diagrams due to a console error in the Viewer. Can I provide you with any more information on reproducing the issue? Will this be fixed in the next couple sprints. 

BTW - We're building an app using TUI as the editor. This [page](https://github.com/writepubapp/welcome/blob/master/Main.md) has some screenshots. 

Thank you for an amazing editor library!!

**Comment by kyuwoo-choi** [comment]
sorry for the delay.
sure I'll fix the issue. wait for it :)

**Comment by writepubapp** [comment]
@kyuwoo-choi  - Can't thank you enough for the quick fix!
