### ISSUE TITLE
Add CONTRIBUTING.md file

### ISSUE THREAD

**Issue by GorgonsMaze** [nhnent/tui.editor#23]
Awesome project. I'm interested in making some PR but I'm curious the best branch to open pull requests to? 

I'd like suggest for future contributions to this project, to create a CONTRIBUTING.md file with some guidelines on contributing, the Pull Request process, and code of conduct that the maintainers of this project would like.

Thanks!

**Comment by kyuwoo-choi** [comment]
hey @GorgonsMaze good to hear some advice & pr.

I see you confused what branch you start commit. I think I should prepared the docs.

Thanks!
