### ISSUE TITLE
Adding link to images breaks them

### ISSUE THREAD

**Issue by HACKHERS** [nhnent/tui.editor#237]
## Version
v1.2.3

## Test Environment
Chrome 67.0.3396.99 / Windows 10

## Current Behavior
When you add link to the image it escapes the image with `\`.
Before:
`![image](https://cloud.githubusercontent.com/assets/389021/16107646/9729e556-33d8-11e6-933f-5b09fa3a53bb.png)`
After:
`[!\[image\]\(https://cloud.githubusercontent.com/assets/389021/16107646/9729e556-33d8-11e6-933f-5b09fa3a53bb.png\)](test.com)`

## Expected Behavior
It should be something like this:
`[![image](https://cloud.githubusercontent.com/assets/389021/16107646/9729e556-33d8-11e6-933f-5b09fa3a53bb.png)](test.com)`

Notes: You can test it on [TUI Editor Website](http://ui.toast.com/tui-editor/) in All Extensions tab.

**Comment by sohee-lee7** [comment]
@HACKHERS Sorry for late reply. This issue does not occur in latest version so please use latest version. I will close this issue. If you have other problem, please make a new issue. Thank you !!
