### ISSUE TITLE
(Feature request) background color for text

### ISSUE THREAD

**Issue by 1c7** [nhnent/tui.editor#239]
## 1. Right now there are only text color
![image](https://user-images.githubusercontent.com/1804755/42132970-814ff654-7d54-11e8-82e2-a930cc462044.png)

## 2. Reason behind "background color"
I am making a women beauty product forum, I hope the overall mood is more of "fun & relax". 
so more color( not than just black plain text) is very important.

## 3. Any plan on support "background color"?

I understand I may asking too much for a free open source project.
This Github issue is more of asking you guys opinion on this:
  * not gonna implement this because _______ (time, money, etc)
  * would add this soon
  * etc.

Any thought?

## 4. I am also looking through document， see if I can implement this.

Thank you very much

**Comment by boggye** [comment]
I am interested in this feature as well. How does one implement it to allow the users to highlight portions of text?
