### ISSUE TITLE
When editor de-focuse, focus again:height option is auto

### ISSUE THREAD

**Issue by sagnol** [nhnent/tui.editor#251]
## Version

1.2.3
## Test Environment

Chrome, Edge
## Current Behavior

1. Editor's height option is 'auto'.
2. Compositing Korean, longer than a browser height.
3. When editor de-focuse (clicking-away or click button), focus editor again.

```js
// Write example code
{
  height: 'auto'
}
```
## Expected Behavior

Don't focus editor again. (It seems to be related to 'compotionupdate' event )

**Comment by kyuwoo-choi** [comment]
I've tried to reproduce the problem and I couldn't.

1. have you tried it on markdown or WYSIWYG mode?
2. would you test it again with 1.2.5?

**Comment by sagnol** [comment]
1. WYSIWYG mode
2. 1.2.3

[TEST] Editor's height(auto) is longer than a brower height. (yes, too many text)
But we tested dooray(tui), naver email composer(naver smarteditor) and some other editor(CKEditor, TinyMCE ... etc), The same thing happened in most editors. (_Current Behavior 3_)

**Comment by francisvgi** [comment]
@sagnol 
Do you have an idea how to focus on the editor upon show?

**Comment by sohee-lee7** [comment]
@sagnol I try to reproduce this issue but this issue does not occur. I use the latest version. Please test using the latest version. I will close this issue. If you have problem, please reopen or make a new issue.
