### ISSUE TITLE
（Question) Click image, cursor put below image, not after it

### ISSUE THREAD

**Issue by 1c7** [nhnent/tui.editor#252]
## Question
When click image inside editor, cursor put below image, not after it.   
How do I do that?

## Current behavior
![image](https://user-images.githubusercontent.com/1804755/42411047-7351a07a-8227-11e8-9660-e5472ff90721.png)

## Except
![image](https://user-images.githubusercontent.com/1804755/42411052-867d2dea-8227-11e8-9d7c-76df4f59acf4.png)

## I know
User can just press "Enter"      
But user already feedback says they want cursor below the image. 

## So
How can I do this? Can you give me a short example?
Thank you very much!

**Comment by kyuwoo-choi** [comment]
I recommend not to do.
Images are inline elements and the cursor should be placed after the image.
And markdown syntax expects that too.
Also, I think if the image is small enough, they would want to put the cursor after the image back.

btw. If you really really want to do so, you can implement an event handler which
- runs on next tick to the `command` event with `AddImage` command
- makes a new line and fixes the cursor position
- https://github.com/nhnent/tui.editor/blob/master/src/js/commandManager.js#L115

**Comment by 1c7** [comment]
@kyuwoo-choi  Thank you!
