### ISSUE TITLE
Indent and Outdent doesn't work in WYSIWYG mode.

### ISSUE THREAD

**Issue by karthiikselvam** [nhnent/tui.editor#254]
## Version
v1.2.3

## Test Environment

Chrome / Windows 10
## Current Behavior
1. Indent and Outdent doesn't work in WYSIWYG mode.
2. Indent and Outdent inserts a Codeblock IN Markdown mode.

*Copy paste the below text in WYSIWYG mode 
1.hello
2.John
3.Doe
*Click on Outdent. It doesn't work.
*In Markdown mode it inserts Code block. Is this the expected Behavior.?
## Expected Behavior

 If you do the same in Microsoft word it moves the Text towards right.

**Comment by kyuwoo-choi** [comment]
The behavior has been changed in v1.2.4

Indent/outdent now works on lists only.
unlike MS word, It's a markdown editor, indentation means a blockquote.
I have made the changes as people tend to get confused with it.
