### ISSUE TITLE
need to review docs

### ISSUE THREAD

**Issue by kyuwoo-choi** [nhnent/tui.editor#26]
I think a lot of sentences can be better as English is not my first language.
Please feel free to make a PR and become a contributor!
Translation is also welcomed.

[readme](https://github.com/nhnent/tui.editor/blob/master/README.md)
[getting started](https://github.com/nhnent/tui.editor/blob/master/docs/getting-started.md)
[getting started with bower](https://github.com/nhnent/tui.editor/blob/master/docs/getting-started-with-bower.md)
[using extensions](https://github.com/nhnent/tui.editor/blob/master/docs/using-extensions.md)

**Comment by SetCodesToFire** [comment]
Hi I want to help you in this. Can i contribute?

**Comment by kyuwoo-choi** [comment]
@SetCodesToFire Sure! go ahead and give me a PR 😄

**Comment by kyuwoo-choi** [comment]
Hey @SetCodesToFire I think you need to follow https://help.github.com/articles/syncing-a-fork/
Cheers!

**Comment by SetCodesToFire** [comment]
Hi @kyuwoo-choi thank you so much.

**Comment by SetCodesToFire** [comment]
@kyuwoo-choi I am still facing issues. What could be done ,can you please help. I cannot get how to work on your master branch. I have forked the repo, then cloned it in my local drive, then i am doing git checkout -b master, which switches me to master branch, then i did the necessary changes and at last git checkout and git push origin master.

But when i am trying to push it,an error is shown on the screen telling that the files that i have cloned is some commits before the master branch,to push the file ,first i have to make a pull.

Is there a work around in this like i have to first clone the repo and then pull your master branch?

**Comment by kyuwoo-choi** [comment]
hey @SetCodesToFire 

`git checkout -b master` won't do anything because what it does is creating a new branch named master which is already exist.
`git checkout master` will switch to master which is you'll want.

and you can not push to this repo directory. it's locked.

I see you have a commit in `production` branch in your repo.
So this time, just try again without `-b` when you switch the branch to master.

Thanks for your effort 👍

**Comment by SetCodesToFire** [comment]
Finally did it. 👍 Thank you so much for appreciating me @kyuwoo-choi .
