### ISSUE TITLE
(Feature request) Center image in Editor (also image take entire row)

### ISSUE THREAD

**Issue by 1c7** [nhnent/tui.editor#262]
### Image in center & take entire row (no text on the same row)

<img width="835" alt="123123" src="https://user-images.githubusercontent.com/1804755/42672227-3b422672-8697-11e8-874e-602df2f0b357.png">

## I understand it may be too much to ask
Can you tell me how can I implement this myself, what direction should I take?
just change some CSS? or ?

Thank you very much!

**Comment by kyuwoo-choi** [comment]
we **currently** don't support html in markdown except span with color style.
(they'll be removed when you swith modes)

the only option we have now is css with some tweeks I guess.
please refer to #30 

I'll mark it feature request.

**Comment by 1c7** [comment]
@kyuwoo-choi Thank you
