### ISSUE TITLE
Preview-editor possible?

### ISSUE THREAD

**Issue by Eraldo** [nhnent/tui.editor#280]
Is it already possible to have a view that is a mix between wysiwyg and markdown?
(Preview and editor in one)
Example: https://laobubu.net/HyperMD

**Comment by kyuwoo-choi** [comment]
nope. the two modes cannot be merged in our editor.
I'm thinking the merged editor is a next big step for the future.

**Comment by sohee-lee7** [comment]
Currently this feature is not in plan. So I will close it.
