### ISSUE TITLE
Removing rows/cols destroy wrapper table

### ISSUE THREAD

**Issue by arxeiss** [nhnent/tui.editor#290]
## Current Behavior
I have table and inside one cell I have `div` containing editor.
If in editor is a table, and I want to remove column or row, removed is column or row from the most outside table. Which is not in editor at all.

```html
<table>
    <tr>
        <td>
            <div id="tui_editor">
                ...
                    <!-- Let's assume, this is content of editor -->

                    <table>
                        <tr>
                            <td>DELETING THOSE cols or rows</td>
                            <td>actually delete cols or rows</td>
                        </tr>
                        <tr>
                            <td>of the most outside table</td>
                            <td></td>
                        </tr>
                    </table>
                ...
            </div>
        </td>
    </tr>
</table>
```

**Comment by sohee-lee7** [comment]
@arxeiss Sorry, I'm late for reply. I don't understand your question. Do you want to remove table in outside table by programmatically?? We not support this function. 
This issue is old so i will close. If you have more question, make a new issue.
Again I'm sorry to late reply..
