### ISSUE TITLE
npm install pull from github with commit id

### ISSUE THREAD

**Issue by rickywu** [nhnent/tui.editor#294]
I use my private npm source, but one of tui-editor dependency is squire-rte which must pull from github

this cause npm install failed on my internal server, could you fix?

**Comment by kyuwoo-choi** [comment]
Sorry to hear that.
Head of official squire-rte has a commit which incompatible to our editor.
we need to resolve the issue before we depend on the official one.

**Comment by sohee-lee7** [comment]
@rickywu We update Squire to 1.9.0 version that is official version.

**Comment by rickywu** [comment]
@seonim-ryu @sohee-lee7 
Could you fix v1.4.10 install from github?

git://github.com/adobe-webplatform/eve.git#eef80ed8d188423c2272746fb8ae5cc8dad84cb1
github:nhn/karma-webdriver-launcher#9dda6755e8fe9d22414df69a78375d8c5774ad6c
git+https://github.com/nhn/raphael.git#78a6ed3ec269f33b6457b0ec66f8c3d1f2ed70e0
github:seonim-ryu/Squire#fd40b4e3020845825701e9689f190bab3f4775d4
git+https://github.com/nhn/raphael.git#2.2.0-c
