### ISSUE TITLE
toolbox 가운데 정렬기능 문의

### ISSUE THREAD

**Issue by jiee0220** [nhnent/tui.editor#296]
안녕하세요. 

editor에서 좌측/우측 정렬은 있는데

가운데 정렬 기능도 함께 사용하고 싶습니다.

toolbox에 버튼하나 추가해서 가운데 정렬 기능을 사용할 수 있는 방법이 있을까요?

가이드 부탁드립니다.

**Comment by kyuwoo-choi** [comment]
음.. 어떤 말씀이신지 알 수 없네요.
우리 에디터는 마크다운 위지윅 에디터이고, 마크다운 문법상 정렬은 지원할 수 없는 기능입니다.
좌/우/가운데 어떤 것도요.

혹시 테이블 안의 내용 정렬 질문이시라면,
이미 좌/우/가운데 정렬이 있습니다.
