### ISSUE TITLE
Open/init in WYSIWYG-mode

### ISSUE THREAD

**Issue by JohanM87** [nhnent/tui.editor#297]
Can anyone please tell me what’s the best way to open the editor in WYSIWYG-mode so you don’t have to toggle to this mode manually in the bottom right corner?

**Comment by mdchaney** [comment]
`$('#' + div_id).tuiEditor({
        initialEditType: 'wysiwyg',
...`

This is covered well in the docs and shouldn't be in issues.

**Comment by JohanM87** [comment]
Ah that easy, I was way overthinking it. Thanks so much!
