### ISSUE TITLE
HTML lost in WYSIWYG mode

### ISSUE THREAD

**Issue by rhukster** [nhnent/tui.editor#30]
I've been looking for a solid WYSIWYG markdown editor for some time, and Toast looks very promising!  I've just been testing with the demo and noticed an issue with HTML in markdown.  As you know putting HTML code in markdown is perfectly valid, and often is the only way to achieve something beyond the capabilities of markdown (adding a class or id for example).  in the `Markdown` mode, things look ok:

```markdown
# markdown

<div class="html">HTML</div>

**more markdown**
```

and renders in the preview fine (even with `class="html"` intact):

![nhn entertainment 2018-01-10 12-31-42](https://user-images.githubusercontent.com/1084697/34791452-3e846b5e-f602-11e7-91c5-50c25b421f76.png)

However, switching to `WYSIWYG` mode and back to `Markdown` causes a loss of the HTML:

![nhn entertainment 2018-01-10 12-32-32](https://user-images.githubusercontent.com/1084697/34791478-57ede4bc-f602-11e7-8026-8cb6f51fcc1d.png)

It would be great (and much safer for users) if this could be maintained between modes.

**Comment by kyuwoo-choi** [comment]
Yes putting html in MD is valid. But currently we have some rules sanitizing html tag except something like `<span style="color~~~ >` which is needed to color text while switching mode.
I'll discuss about this problem with our team members.

Thanks for the issue :)

**Comment by ViggoV** [comment]
@kyuwoo-choi sorry if this is the wrong place to ask, but are these sanitizing rules documented somewhere? We are looking to use tui to update news on our website and are quite interested in knowing how html tags are treated, mainly in terms of vulnerabilities..

**Comment by kyuwoo-choi** [comment]
@ViggoV Not at all. Any questions are welcome.
Check https://github.com/nhnent/tui.editor/blob/master/src/js/htmlSanitizer.js to see which rules are applied.

I think the rules are a bit defensive because we did not have enough time to make it fine grind.
It may be a good time / place to discuss.

**Comment by kyuwoo-choi** [comment]
+ we should consider the way **html2md**, **md2html** and how to treat those while **editing tags in WYSIWYG mode**.

**Comment by ViggoV** [comment]
Thanks! I can't help but notice that you strip `form`, `button`, `select` and `textarea` but apparently not `input`.. Is that on purpose?

**Comment by kyuwoo-choi** [comment]
@ViggoV Nothing I remember. I think I will investigate the commits. Thanks!

**Comment by moyiblog** [comment]
## How to get MD or HTML

**Comment by cavo789** [comment]
Hello

Same question and didn't find how to deal with it. Can somebody help please ?

I try to edit a file like, f.i., 

```markdown
# TOC
<div>TEST</div>
```
The editor has removed the HTML tag so display : 
```markdown
# TOC
TEST
```
If I save that content, I'll lose my original content.

My problem : I'm using span, div, img and also my own tag called "<encrypt>" and I wish to be able to keep them in the editor.

Note : I didn't see any difference by setting `useDefaultHTMLSanitizer` to false in my constructor.

```javascript
	var editor = new tui.Editor({
		...
		"useDefaultHTMLSanitizer": false
		...
	});
```

Thank you!

**Comment by sohee-lee7** [comment]
This issue is old and will be closed. If there is an issue again, please register as a new issue.
