### ISSUE TITLE
span tag escaped when switching from markdown to wysiwyg mode (3MD)

### ISSUE THREAD

**Issue by akiander** [nhnent/tui.editor#300]
## Version
1.2.6

## Test Environment
Chrome / Windows

## Current Behavior
When switching from markdown mode to wysiwyg mode on the editor, any portion of a code block that is highlighted gets escaped. 

For example, if our codeblock contains 

```
here is code with a  <span class="hl hl-1">highlighted</span> word
```

Then when we switch from markdown to wysiwyg mode, the span tag that highlights the word is escaped so it is no longer shown to the user as highlighted. 

## Expected Behavior
Is there a way to modify the behavior of the tui-editor so that we can avoid having some span tags escaped when switching modes?

**Comment by akiander** [comment]
I created a repro for this issue [here](https://github.com/akiander/TuiPg) based off the most recent angular 6 new project template. 

Just clone it and run command `ng serve --open`

You should notice that when in markdown mode, highlighting inside the code block is shown to the user in the markdown viewer. But when you switch to WYSIWYG mode, the highlighting disappears. 

All help diagnosing and fixing this issue would be appreciated.

**Comment by akiander** [comment]
I now have a working demo of this issue [here](https://akiander.github.io/TuiPg/)

**Comment by akiander** [comment]
Does anyone have any ideas regarding how to fix this? 

I can see that [this line of code](https://github.com/nhnent/tui.editor/blob/ad7222a6af6a160bf135051dbb4903bd78b53f73/src/js/wwCodeBlockManager.js#L321) is the cause for all of the code block content getting escaped. 

There doesn't appear to be any way to change this behavior via settings. I can replace the `wwCodeBlockManager` class entirely but the control appears to just ignore the new class I inject. 

I am hoping to get some advice on how I should solve this. Does anyone have any thoughts?

**Comment by sohee-lee7** [comment]
@akiander I'm sorry for late reply. I think this issue is bug. We try to fix this issue.

**Comment by sohee-lee7** [comment]
Amount of work : 3MD

**Comment by sohee-lee7** [comment]
@akiander The code you did point is cause of problem. This issue would be fixed in next release. Thank you!
