### ISSUE TITLE
A bug caused by require('highlight.js')

### ISSUE THREAD

**Issue by qiujiangkun** [nhnent/tui.editor#307]
Because of require('highlight.js') in each tui.editor.xxx.js file, requirejs will try to find file 'highlight.js' in current directory.
Hope to fix this bug by replacing 'highlight.js' by 'highlightjs'

**Comment by sohee-lee7** [comment]
@qiujiangkun Please give me more accurate information. `tui.editor` has dependency [highlight.js](https://www.npmjs.com/package/highlight.js).

**Comment by sohee-lee7** [comment]
I'm glad it's resolved. Then I'll close the issue.
