### ISSUE TITLE
Id for the heading tags html

### ISSUE THREAD

**Issue by GGui** [nhnent/tui.editor#308]
Hi,

I would like to manage anchor in my links.
To manage the anchors in my link, i need a id on heading tags html (h1,h2,h"..).
Is there a configuration available to active that?

Thank you

**Comment by sohee-lee7** [comment]
@GGui I'm sorry for the late reply. Currently, we do not provide the ability to id the tags inside the editor.

**Comment by sohee-lee7** [comment]
This is old so I will close it.

**Comment by lijundong** [comment]
i manually add id to head tag before generate toc

**Comment by bwl21** [comment]
> i manually add id to head tag before generate toc

how do you add it to head tag?
