### ISSUE TITLE
Prevent default key event handlers from firing

### ISSUE THREAD

**Issue by Justas-S** [nhnent/tui.editor#309]
## Version
1.2.6

## Test Environment
All

## Current Behavior
When listening for a key event like `ENTER`, there is no way to disable default behavior. In wysiwg mode it is possible to prevent Squire behavior, to not enter a new line. But if you press enter while on a header line, tui.editor will remove the header. 

## Expected Behavior
A mechanism, similar to native events that allows to `preventDefault` tui.editor behavior.

**Comment by Justas-S** [comment]
Managed to prevent default key events by [adding a key handler](addKeyEventHandler) to the `DEFAULT` key map, although this is only valid for the wysiwyg editor.

**Comment by sohee-lee7** [comment]
@Justas-S Sorry for late reply. There is no way to prevent default behavior. Is your original issue that header is removed when enter? Please use the latest version and check this issue still occurs.
We need more discussion how to prevent default behavior.

**Comment by Justas-S** [comment]
I'm not sure what I meant exactly but I could not reproduce anything similar with the latest release.
