### ISSUE TITLE
Code blocks causing issues when toggling modes

### ISSUE THREAD

**Issue by rhukster** [nhnent/tui.editor#31]
Like the previous issue I posted, switching between `Markdown` and `WYSIWYG` modes also causes issues for codeblocks.  Take the example code:

![nhn entertainment 2018-01-10 12-35-33](https://user-images.githubusercontent.com/1084697/34791648-c9e719da-f602-11e7-9869-7fe2ab310f56.png)

Toggling to `WYSIWYG` and back to `Markdown` causes the code to be wrapped in backticks:

![nhn entertainment 2018-01-10 12-36-07](https://user-images.githubusercontent.com/1084697/34791676-e1c1eb5c-f602-11e7-8e0e-65f25d045ab0.png)

Repeating this process results in more backticks:

![nhn entertainment 2018-01-10 12-36-50](https://user-images.githubusercontent.com/1084697/34791701-f301a57e-f602-11e7-840d-2a949a416d3f.png)

**Comment by kyuwoo-choi** [comment]
It is a clearly a bug. I'll try patch this soon.

**Comment by kyuwoo-choi** [comment]
dedup #65
