### ISSUE TITLE
Name attribute on the editor's div not recognised when submiting to server

### ISSUE THREAD

**Issue by GabMic** [nhnent/tui.editor#313]
## Version
Latest version via NPM

## Test Environment

Chrome, on windows 10
## Current Behavior

It's all working on the browser, but when i submit it, it wont recognize the `name` attribute on it. How or where should i add a name attribute to the editor so i can send to my server?

```html
<div id="editor" name="body"></div>
```

## Expected Behavior

I expected the name attribute (that i am giving on the editor div to be recognised, like so: 

`<div id="editor" name="body"></div>`

Thanks for the help.

**Comment by GabMic** [comment]
Anyone, please?

**Comment by sohee-lee7** [comment]
@GabMic I'm sorry for the late reply. It's not what we manage about the name attribute of the editor's element. Therefore, you have to implement in your code for controlling name attribute.

**Comment by sohee-lee7** [comment]
This issue is old so close it. If you have problem, please make a new issue.
