### ISSUE TITLE
Missing toolbar icons

### ISSUE THREAD

**Issue by jhefreyzz** [nhnent/tui.editor#316]
## Version

tui-editor@1.2.6
## Test Environment

Google Chrome Version 70.0.3538.77 
### Technology used:
- Webpack
- Phoenix Framework

## Steps to reproduce
- Add tui-editor
- Follows the code in the read MD for tui-editor usage.

```js
require('codemirror/lib/codemirror.css'); // codemirror
require('tui-editor/dist/tui-editor.css'); // editor ui
require('tui-editor/dist/tui-editor-contents.css'); // editor content
require('highlight.js/styles/github.css'); // code block highlight

const Editor = require('tui-editor');

const editor = new Editor({
  el: document.querySelector('#editSection'),
  initialEditType: 'markdown',
  previewStyle: 'tab',
  height: '300px',
  usageStatistics: false
});

//webpack-config.js
const path = require('path');
const glob = require('glob');
const MiniCssExtractPlugin = require('mini-css-extract-plugin');
const UglifyJsPlugin = require('uglifyjs-webpack-plugin');
const OptimizeCSSAssetsPlugin = require('optimize-css-assets-webpack-plugin');
const CopyWebpackPlugin = require('copy-webpack-plugin');

module.exports = (env, options) => ({
  optimization: {
    minimizer: [
      new UglifyJsPlugin({ cache: true, parallel: true, sourceMap: false }),
      new OptimizeCSSAssetsPlugin({})
    ]
  },
  entry: {
    './js/app.js': ['./js/app.js'].concat(glob.sync('./vendor/**/*.js'))
  },
  output: {
    filename: 'app.js',
    path: path.resolve(__dirname, '../priv/static/js')
  },
  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader'
        }
      },
      {
        test: /\.(png|jpg|gif)$/,
        use: [
          {
            loader: 'file-loader',
            options: {}
          }
        ]
      },
      {
        test: /\.css$/,
        use: [MiniCssExtractPlugin.loader, 'css-loader', 'postcss-loader']
      }
    ]
  },
  plugins: [
    new MiniCssExtractPlugin({ filename: '../css/app.css' }),
    new CopyWebpackPlugin([{ from: 'static/', to: '../' }])
  ]
});

```
- Tui-editor works although the toolbar icons are missing.

![screenshot from 2018-11-04 12-27-45](https://user-images.githubusercontent.com/20869829/47960000-27c25f00-e02d-11e8-976d-8d1dca6ceaa0.png)
![screenshot from 2018-11-04 12-29-56](https://user-images.githubusercontent.com/20869829/47960012-62c49280-e02d-11e8-9094-a956b7f8bff1.png)

## Expected Behavior

Should display to toolbar icons.

**Comment by Linshiqi** [comment]
Did you fix it?  I have similar problem, see issue 399, would you give me some advise? Thank you!

**Comment by sohee-lee7** [comment]
@Linshiqi Is this issue still happening? If still happen, please give more detail information.

**Comment by Linshiqi** [comment]
@sohee-lee7 I have fixed it in other way, The issue is closed, Thank you >_<

**Comment by maronin-vention** [comment]
> @sohee-lee7 I have fixed it in other way, The issue is closed, Thank you >_<

How did you fix this?

Edit: I had a problem with my webpack.config file, where "file-loader" would break things. It would exclude a bunch of extensions of files, but I guess somehow it was affecting the URI images coming the css files... I just got rid of it and it works fine now!
