### ISSUE TITLE
Angular component version ?

### ISSUE THREAD

**Issue by j-kwan** [nhnent/tui.editor#318]
Hi,
I'm trying to use TUI editor in Angular. 
And I was wondering if there is a version of TUI Editor as component.
Is there an official angular component version or a more recent and mantained version than this [one](https://www.npmjs.com/package/ngx-tui-editor) ?

**Comment by sohee-lee7** [comment]
Unfortunately, there is no official support for Angular. Please wait for the future plans to support Angular.
