### ISSUE TITLE
How can i set/insert data into the editor with a function?

### ISSUE THREAD

**Issue by GabMic** [nhnent/tui.editor#320]
I am using the latest version via NPM.
I was wondering, how can i insert data into the editor after i have instantiated it?

I required it like so: 

```js
var Editor = require('tui-editor');
var editorElement = document.getElementById('editor');
var editor = new Editor({  
  el: editorElement,
    initialEditType: 'wysiwyg',
    height: '300px',
});
```

```html
<div id="editor"></div>   
```

and it's showing the editor correctly.

**Comment by sohee-lee7** [comment]
If you use `setValue`(http://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#setValue), you can insert text into the editor.
