### ISSUE TITLE
Missing library files in repository

### ISSUE THREAD

**Issue by tribis** [nhnent/tui.editor#324]
## Version

1.2.6/master

## Test Environment

not applicable

## Current Behavior

The examples in the the ./examples directory present HTML pages with links to the required dependencies, as shown below:
```html
<head lang="en">
    <meta charset="UTF-8">
    <title>0. DEMO</title>
    <script src="../lib/jquery/dist/jquery.js"></script>
    <script src="../lib/markdown-it/dist/markdown-it.js"></script>
    <script src="../lib/to-mark/dist/to-mark.js"></script>
    <script src="../lib/tui-code-snippet/dist/tui-code-snippet.js"></script>
    <script src="../lib/tui-color-picker/dist/tui-color-picker.js"></script>
    <script src="../lib/codemirror/lib/codemirror.js"></script>
    <script src="../lib/highlightjs/highlight.pack.js"></script>
    <script src="../lib/squire-rte/build/squire-raw.js"></script>
    <link rel="stylesheet" href="../lib/codemirror/lib/codemirror.css">
    <link rel="stylesheet" href="../lib/highlightjs/styles/github.css">
    <link rel="stylesheet" href="./explain.css">
  </head>
```
However the directory ./lib/ with all the deps is not present in the repository.
## Expected Behavior

Can you please add that directory? That would help to actually use this nice software in a reliable way. Currently, due to issues #53 and #274 it is very difficult to set it up in a way one can be sure it is the intended way.

**Comment by Lin-H** [comment]
For now you can use `bower install` to install those dependencies.
