### ISSUE TITLE
Webpack Error

### ISSUE THREAD

**Issue by CindyBoy** [nhnent/tui.editor#332]
## Version

![image](https://user-images.githubusercontent.com/19368643/48757188-e68da880-ecd6-11e8-8a35-daac17f123a3.png)

## Test Environment

![image](https://user-images.githubusercontent.com/19368643/48757213-f73e1e80-ecd6-11e8-948f-ae8273c2f6d0.png)

## Current Behavior

version 1.2.7
```js
var Editor = require('tui-editor');
var editor = new Editor({
    el: document.querySelector('#editSection'),
    initialEditType: 'markdown',
    previewStyle: 'vertical',
    height: '300px'
});
```

## Expected Behavior

![image](https://user-images.githubusercontent.com/19368643/48757345-60be2d00-ecd7-11e8-8467-cc2a00c646e8.png)

**Comment by clicksistema** [comment]
actually I'm getting same error. I'm loading throught CDN and I've already tryed to update my jquery link and insert others dependencys of exemples but it stills.

and if I try to use the usual arquive "tui-editor-Editor.js" I get :
Uncaught TypeError: Cannot read property 'Map' of undefined
on line 354:
this._langs = new _tuiCodeSnippet2.default.Map();


my code after all trys:
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.42.0/codemirror.js"></script>
    <script src="https://uicdn.toast.com/tui-editor/latest/tui-editor-Editor.js"></script>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/codemirror/5.42.0/codemirror.css">
    <link rel="stylesheet" href="https://uicdn.toast.com/tui-editor/latest/tui-editor.css">
    <link rel="stylesheet" href="https://uicdn.toast.com/tui-editor/latest/tui-editor-contents.css">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/highlight.js/9.13.1/styles/github.css">

        <div id=textarea_ferramentas></div>

	<script>
    	$('#textarea_ferramentas').tuiEditor({
            initialEditType: 'markdown',
            previewStyle: 'vertical',
            height: '300px'
        });

**Comment by sohee-lee7** [comment]
@CindyBoy Could you provide more information about the test environment?
