### ISSUE TITLE
setting i-beam pointer on empty space in markdown will make better UX

### ISSUE THREAD

**Issue by ParkSB** [nhnent/tui.editor#34]
## Version

v1.0.1
## Test Environment

Chrome  63, Firefox developer edition 58
## Current Behavior

텍스트 박스 상에서 텍스트를 작성한 행 위에 커서를 올리면 ibeam 커서가 나타나지만, 텍스트를 작성하지 않은 빈 공간에 커서를 올리면 기본 arrow 커서가 나타납니다.

## Expected Behavior

대부분의 에디터가 편집 섹션에는 기본적으로 ibeam 커서를 나타나게 하고 있는 만큼, 사용자 경험 측면에서 빈 공간에도 ibeam 커서를 나타나게 하는 게 더 낫지 않을까 생각합니다.

**Comment by kyuwoo-choi** [comment]
저희 에디터에 관심 주셔서 감사합니다 ❤️ 

좋은 아이디어네요. 사실 인지하면서도 워낙 바빠서 신경 못쓰고 있던부분인데 ㅜㅜ
제안 주신만큼 반영될 수 있도록 하겠습니다.

앞으로도 의견 있으면 꼭 이슈 남겨주세요.

ps. 타이틀 제목을 제가 수정했습니다. 😢 
외국인들도 같이 쓰는 만큼 이슈 관련되서 커밋이 올라갈때 적어도 추측은 할 수 있도록 하려합니다.
