### ISSUE TITLE
Markdown Editor for endusers?

### ISSUE THREAD

**Issue by anishmittal2020** [nhnent/tui.editor#341]
Please forgive, I tried to understand but I am not sure on, how this can be used for my application.

I am an end-user, who takes notes in markdown. I saw that the installation via npm is meant to be installed locally. So, can I install it globally, and can I edit `.md` files in my system using this editor.

Please clarify if I have understood this correctly - it is not meant to be used directly by end-users, but by software developers would like to have a markdown editor as a part of their application? Did I understand it correctly?

Is it similar to [marktext/marktext: 📝Next generation markdown editor, running on platforms of MacOS Windows and Linux.](https://github.com/marktext/marktext)?

**Comment by sohee-lee7** [comment]
What you understand is correct. tui.editor is running on browser. If your project is a web project, you can include Markdown editor using tui.editor.
