### ISSUE TITLE
npm install package error: tui-editor and tui-chart

### ISSUE THREAD

**Issue by sunnyke** [nhnent/tui.editor#342]
Hi, npm install error, please look at:

1.tui-chart package.json:
https://github.com/nhnent/tui.chart/blob/master/package.json
"raphael": "https://github.com/nhnent/raphael.git#2.2.0-c",
should be:
"raphael": "2.2.7"

2.tui-editor package.json:
https://github.com/nhnent/tui.editor/blob/master/package.json
"squire-rte": "github:sohee-lee7/Squire#fde64d0bedb524e4495f3121dce518b94ad5852b",
should be:
"squire-rte": "1.9.0"

**Comment by sunnyke** [comment]
Can you fix it and release a new version, our team is using your great product now.

**Comment by sohee-lee7** [comment]
We have plan to update Squire. For update raphael, we should request to update to maintainer of tui-chart.

**Comment by sohee-lee7** [comment]
@sunnyke squire is update to v1.9.0. If use tui-editor v1.3.0, you can use squire v1.9.0. For update raphael, you need to wait for the chart to update. Please contact the [tui.chart](https://github.com/nhnent/tui.chart/issues/) for a schedule for updating the tui.chart.
