### ISSUE TITLE
Wysiwig 내용 서버에 전달할 때 문의

### ISSUE THREAD

**Issue by jhboyo** [nhnent/tui.editor#344]
## Version
1.2.9

## Test Environment
winodws10

## Current Behavior
Editor 의 Wysiwig 에서 작성한 내용을 서버에 전달하려고 합니다.
Editor에 작성한 value를 어떻게 가져와야 하는지 문의 드립니다.

Wysiwig를 적용 전 textarea 속성으로 했을 때는 name 속성으로 처리를 했지만' div id="editSection"  으로 했을 때 value를 어떻게 가져와야 한는지요...

```js
<div id="editSection"></div>
```

**Comment by sohee-lee7** [comment]
```js
var Editor = require('tui-editor');
...
var editor = new Editor({
    el: document.querySelector('#editSection'),
    initialEditType: 'markdown',
    previewStyle: 'vertical',
    height: '300px'
});

var text = editor.getValue();
```
https://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#getValue

getValue함수로 가져올 수 있습니다.
