### ISSUE TITLE
After post or put data to server, the tab or space will be question mark.

### ISSUE THREAD

**Issue by kirin-yuen** [nhnent/tui.editor#347]
## Version
1.2.9

## Test Environment
Chrome 70.0.3538.77 64,  WINDOWS 7

## Current Behavior
I use tui.editor in vue single file, 

```html
<pre v-html="myValue"></pre>
```

edit following content in wysiwyg mode editor
```js
{
    name: 'kirin'
}
```

and after post or put this content to server, it will be question mark that fetch from the serve.

like
```js
{
????name:'kirin'
}
```

my .vue source code
```js
'script'
import Editor from "@toast-ui/vue-editor/src/Editor.vue";
'template'
<Editor mode="wysiwyg" previewStyle="vertical" v-model="myValue"></Editor>
```

## Expected Behavior
The tab can exactly render in 
```html
<pre v-html="myValue"></pre>
```

**Comment by sohee-lee7** [comment]
@kirin-yuen Perhaps a question mark has been added on the server. When I test just using vue editor and pre, this problem does not occur. If you still have problems, please give me a more detailed explanation.

**Comment by sohee-lee7** [comment]
This issue is old so I will close. If you have problem, please make a new issue.
