### ISSUE TITLE
Question : how to save ? 

### ISSUE THREAD

**Issue by cavo789** [nhnent/tui.editor#35]
Hi !

Not an issue but a question : I've not yet installed tui.editor and I'm really interested too try it but ... how can we save the content on the server ? 

I'm actually using [Simple MDE](https://simplemde.com/), we can attach on the toolbar a "save" button, retrieve the content of the <div> and send it to the server with Ajax f.i.

Can we does something like that with tui.editor ? Can you provide tips or documentation ? 

Many thanks !!!

Christophe

**Comment by skerbis** [comment]
It just replaces a form-element or div etc. You can save your data like you prefer doing it with other input elements

**Comment by cavo789** [comment]
Thanks for the very fast answer.

So, to take a real example, on the demo page (https://nhnent.github.io/tui.editor/), I click on the "Features" div, type something and see in the DOM inspector that the change is done in the div with class "te-editor" like :

```html
<div class="te-editor" style="position: relative;">
	<div contenteditable="true">
		<h1>
			<div>
				<span class="colour" style="color:rgb(75, 148, 229)">Features MY CHANGES</span>
			</div>
		</h1>
```

Should I foresee a .onChange() js function on that DOM elem to retrieve the change ? (how can I very quickly remove the "<div contenteditable="true">" and only retrieve the editor's content).

Thanks

**Comment by michaelryancaputo** [comment]
I hope this helps you out:

```TuiEditor.factory({
      el: this.el,
      height: 'auto',
      initialValue: determineValue(this.props),
      initialEditType: 'wysiwyg',
      events: {
        change: this.onChange,
        focus: () => this.props.input.onFocus(),
        blur: () => this.props.input.onBlur(),
      },
    })```

**Comment by kyuwoo-choi** [comment]
@skerbis @michaelryancaputo Thanks guys. I see we have good contributors 💯 

@cavo789 in addition, you can check out [API Docs](https://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html) `constructor options`

I'm closing it.

**Comment by cavo789** [comment]
Thank you guys !!!  Thank you Michael for your js code (y)

**Comment by moyiblog** [comment]
@michaelryancaputo Can write a detailed code for getHtml and getMarkdown, because I have made a mistake in copying your code, and my javaScript is not proficient

**Comment by iChard** [comment]
Thank you guys!!
