### ISSUE TITLE
Question : Can we load a dictionnary (French one f.i.) ?

### ISSUE THREAD

**Issue by cavo789** [nhnent/tui.editor#36]
By looking the HTML of the editor, I see that you've already foresee a "spellcheck" attribute

```html
<div contenteditable="true" class="tui-editor-contents" ....  spellcheck="false" ....>
```

Is it possible to specify the language for the spellcheck ? (french, dutch, english, ...)

Many thanks

**Comment by kyuwoo-choi** [comment]
hey @cavo789  thank you for your interest in our editor.

There's no API/Option our editor provides, and you're free to set it on your code.

welcomed always 😄

**Comment by cavo789** [comment]
Thanks for the answer KyuWoo.
