### ISSUE TITLE
Pasting from MS word document.

### ISSUE THREAD

**Issue by oni7uka** [nhnent/tui.editor#363]
## Version
1.2.10

## Test Environment

Chrome(latest,  71.0.3578.98)
## Current Behavior

When i copy the content from ms word to tui editor( wysiwtyg mode) , it's  not correct break lines.
This is a test example:
![issue](https://user-images.githubusercontent.com/15939343/51104006-bf0f1400-181f-11e9-8123-dfca6b5b64d8.png),

Paste the content to wysiwtyg  area, then switch to markdown mode. the result: 
```
Diana
used to \_\_\_\_\_\_ to work\, but now she is used to \_\_\_\_\_\_ because the road is crowded
and she wants to keep fit\.
```
WHY tui break line after first word, but not after 'is' ?

The issue can repeat on Official website demo page [Tui edtor](http://nhnent.github.io/tui.editor/api/latest/tutorial-example01-basic.html) 

[sample.docx](https://github.com/nhnent/tui.editor/files/2754541/sample.docx)

**Comment by oni7uka** [comment]
Ok. it looks like Squire's problem.

**Comment by sohee-lee7** [comment]
Squire first use `text/html` of clipboardData to paste. If copy text of sample.docx, 'text/html' include below data.
```html
<p class=MsoNormal style='text-indent:6.0pt;mso-char-indent-count:.5;
tab-stops:120.0pt 220.0pt 320.0pt'><span style='font-size:12.0pt'>Diana used to
______ to work, but now she is used to ______ because the road is <o:p></o:p></span></p>

<p class=MsoNormal style='text-indent:6.0pt;mso-char-indent-count:.5;
tab-stops:120.0pt 220.0pt 320.0pt'><span style='font-size:12.0pt'>crowded and she
wants to keep fit.<o:p></o:p></span></p>

<p class=MsoNormal><o:p>&nbsp;</o:p></p>
```
There are line break between `Diana used to`and `______ to work`.

If use `text/plain` of clipboardData , there are no line break between `Diana used to`and `______ to work`.

```
Diana used to ______ to work, but now she is used to ______ because the road is

crowded and she wants to keep fit.
```

This is Squire's problem

**Comment by sohee-lee7** [comment]
@oni7uka We manage this issue #401 so close this issue.
