### ISSUE TITLE
Can i resize the table with mouse click??

### ISSUE THREAD

**Issue by jeetkn** [nhnent/tui.editor#371]
Thank you for this awesome editor!
I want to resize the table with mouse click. 
It is possible???

안녕하세요 이런 좋은 에디터를 만들어 주셔서 정말 감사합니다.
제가 사용하며서 마우스 클릭이나 드래그로 테이블의 사이즈를 변환하고 싶은데 가능할까요???

**Comment by sohee-lee7** [comment]
It is not possible.
