### ISSUE TITLE
Dragging selection does not work in IE11

### ISSUE THREAD

**Issue by suchun0** [nhnent/tui.editor#376]
## Version
v1.3.0

## Test Environment
OS: Windows 10
Browser: IE11

## Current Behavior
https://nhnent.github.io/tui.editor/api/latest/tutorial-example01-basic.html

1. Place the cursor at the selection staring point.
2. Try dragging to make a selection.
3. Can figure out dragging selection does not work

## Expected Behavior
- Dragging selection correctly work

**Comment by sohee-lee7** [comment]
The cause for this issue is registered in the CodeMirror issue. (https://github.com/codemirror/CodeMirror/issues/5759)

**Comment by sohee-lee7** [comment]
The history is too old to find out why calls `refresh` in `focus` event handler of CodeMirror. And I did not have any problems when I changed the `focus` event to not call `refresh`. I also heard from the CodeMirror maintainer that the `refresh` is expensive and is not a good call to the `focus` event. So I will change it to not call `refresh`.
