### ISSUE TITLE
JS Errors When Loading the Editor

### ISSUE THREAD

**Issue by cyberjacob** [nhnent/tui.editor#385]
## Current Behavior

When attempting to load the editor (e.g. https://codepen.io/anon/pen/rPzgVG?editors=1010 ), the editor does not load, and one of two JS errors are shown in the console:
```js
TypeError: tui.Editor is not a constructor
```

```js
Error: Syntax error, unrecognized expression: <div class="tui-editor-defaultUI"> <div class="te-toolbar-section"><div class="te-markdown-tab-section"></div></div> <div class="te-editor-section"></div> <div class="te-mode-switch-section"></div> </div>
```
## Expected Behavior

The editor loads.

**Comment by cs09g** [comment]
Similiar error is happening with jsfiddle: https://jsfiddle.net/Lrb6hqtk/

**Comment by cs09g** [comment]
After a bit of investigation, found it required many dependencies:
- jquery.js, markdown-it.js, to-mark.js, tui-code-snippet.js, codemirror.js, highlight.pack.js, squire-raw.js

In your case, if you add jquery, it will work as expected.
`<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.js"></script>`

codepen: https://codepen.io/anon/pen/ZwjxoY

**Comment by sohee-lee7** [comment]
@cyberjacob tui.editor have dependencies of jquery, markdownIt and etc. [tui-editor-Editor-full.js](https://uicdn.toast.com/tui-editor/latest/tui-editor-Editor-full.js) is bundled with all dependencies. So if you don't want to load dependecies,  use `tui-editor-Editor-full.js`

**Comment by sohee-lee7** [comment]
@cyberjacob I think this issue is resolved so I will close it. If you have any problem, please make a new issue.
