### ISSUE TITLE
html getValue() performance

### ISSUE THREAD

**Issue by Doidel** [nhnent/tui.editor#398]
Version: 1.2.7
Test Environment: Google Chrome, Windows 10

Current Behavior:
getValue() in Wysiwyg is slow, and even freezes for e.g. entire books.

Expected Behavior:
Instead of reinventing the wheel, maybe you can use one of the existing html to markdown parsers? markdown-it, showdown-js, any one of those, as they convert much faster. Unfortunately, in the current state I won't be able to use your editor :(
Nonetheless thank you for providing it, it's a great tool!

Kind regards,
Doidel

**Comment by sohee-lee7** [comment]
@Doidel We can not guarantee the performance up to the volume of a book because there is a process of converting the markdown to the above map to provide Wysiwyg.

**Comment by Doidel** [comment]
Alright, thanks for clarifying.
