### ISSUE TITLE
docs: need docs for npm + bundler usage

### ISSUE THREAD

**Issue by de1ck** [nhnent/tui.editor#40]
## Version

tui-editor  v1.0.1
## Test Environment

chrome win10*64
## Current Behavior

```html
// html
<div id="editSection">
    </div>
    <script src="./index.js"></script>

// js
var Editor = require('tui-editor');
require('tui-editor/dist/tui-editor-extScrollSync.js');
//require('tui-editor/dist/tui-editor.css');
//require('tui-editor/dist/tui-editor-contents.css');
//require('codemirror/lib/codemirror.css')
//require('highlight.js/styles/github.css');
var editor = new Editor({
    el: document.querySelector('#editSection'),
    initialEditType: 'markdown',
    previewStyle: 'vertical',
    height: '300px',
    exts: ['scrollSync'],
    useCommandShortcut: true,
});
```

## Expected Behavior

[docs example Basic](https://nhnent.github.io/tui.editor/api/latest/tutorial-example01-basic.html)
When I don't use this. 
```js
require('tui-editor/dist/tui-editor.css');
require('tui-editor/dist/tui-editor-contents.css');
require('codemirror/lib/codemirror.css')
```
I cant use online edit markdown editor and  ui style is disordered

**Comment by kyuwoo-choi** [comment]
would you tell me more about the problem please?

**Comment by de1ck** [comment]
I think there is something missing in the document, which has caused me a lot of trouble in the process of using it. I hope to have a more friendly document and help the novice to use it.
Such as：
The documentatio lacks some necessary CSS references.  [using-npm](https://github.com/nhnent/tui.editor#-usage)
The following CSS is required for [Editor](https://github.com/nhnent/tui.editor#editor)
```
require('tui-editor/dist/tui-editor.css');
require('tui-editor/dist/tui-editor-contents.css');
require('codemirror/lib/codemirror.css')
```
However, it is not emphasized in the document. Isn't it?

**Comment by kyuwoo-choi** [comment]
oh I get it. Yea I admit it lacking of docs.
I guess you are using npm + webpack. right?
I'll try add more docs for it.

Thank you! ❤️

**Comment by de1ck** [comment]
@kyuwoo-choi  Good！ I'm using yarn + parcel at the moment. .

**Comment by ViggoV** [comment]
Couldn't you at least note in the quick start guide in the readme, that you need to import the styles seperately? The readme gives the impression that all you need to do is import/require the npm module, but when the styles are missing it gives the impression that the editor just doesn't work..

**Comment by kyuwoo-choi** [comment]
@ViggoV yup. I should update.
Bah It’s realy tons of works to do.
I’ll update when I go to work tomorrow.
You can sen me a PR If you want.
