### ISSUE TITLE
Can't set Simplified Chinese After upgraded to 1.3.1

### ISSUE THREAD

**Issue by robertwang1987** [nhnent/tui.editor#418]
## now it Shows Traditional Chinese

```js
// Write example code
const config = {
  language: 'zh_CN',
};
```

## expect Show Simplified Chinese

I  guess it's caused by using the same key
['zh', 'zh_CN']
['zh', 'zh_TW']

**Comment by sohee-lee7** [comment]
@robertwang1987 Thank you for report. This is a bug. We should change key like followings.
```js
i18n.setLanguage(['zh_CN', 'zh_CN']
i18n.setLanguage(['zh_TW', 'zh_TW']
```

**Comment by sohee-lee7** [comment]
@robertwang1987 The key of `zh_CN` keep as `zh` and the key of `zh_TW` change to `zh_TW`.
