### ISSUE TITLE
Focus error when load editor

### ISSUE THREAD

**Issue by LIFOsitory** [nhnent/tui.editor#421]
## Version
1.3.1

## Test Environment

웨일, 크롬, 윈도우
## Current Behavior

페이지 로드시 에디터가 있는 부분까지 페이지가 내려갑니다.
에디터 속성으로 이를 방지 할 수 있나요?

When the page loads, the page goes down to the part where the editor is located.
Can I prevent this with editor properties?

**Comment by sohee-lee7** [comment]
@LIFOsitory I think `scrollSync` extension affect page scroll when loading. Do you use `scrollSync` extension?

**Comment by LIFOsitory** [comment]
No, i don't use scrollSync.
This is the option that I set.
```
var editor = tui.Editor.factory({
    	el: document.getElementById('tuieditor_instance_' + editor_sequence),
        initialEditType: 'markdown',
        previewStyle: editor_previewStyle,
        minHeight: editor_height,
        height: 'auto',
        language: editor_language       
});
```
And I installed the editor by using bower.

**Comment by LIFOsitory** [comment]
OH!! 
I FOUND the reason of this issue.

When editor.setHtml() with no value, page focus to editor.
I just resolve this issue by checking the input value exists.

i think it's minor bug or no problem.
