### ISSUE TITLE
Error applying duplicate effect such as bold and italic text

### ISSUE THREAD

**Issue by Jaemyungku** [nhnent/tui.editor#424]
## Version

1.3.1
## Test Environment

chrome, ie11

## Current Behavior

텍스트에 굵은 글씨와 이탤릭체 등 효과가 중복해서 들어갈 경우
효과가 적용되지 않음

___

Bold and italicized text in duplicate
No effect applied

```js
// Write example code
```

## Expected Behavior

텍스트에 대한 효과가 중복해서 적용될 수 있도록 수정 필요

___
Needs to be modified so that effects on text can be duplicated

**Comment by sohee-lee7** [comment]
@Jaemyungku It was converted to English for other users. This issue may be related #409.
More detail information for this issue. Where does this issue occur in Markdown or Wysiwyg??

**Comment by sohee-lee7** [comment]
This issue is same #409 and resolved that so close it.
