### ISSUE TITLE
NPM Install fails with npm ERR! package.json Non-registry package missing package.json: squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621 #14

### ISSUE THREAD

**Issue by MstaceyMWAM** [nhnent/tui.editor#433]
Version
Latest from NPM

Test Environment
Windows

Current Behavior
npm install --save @toast-ui/vue-editor

Gives error:
npm ERR! code ENOPACKAGEJSON
npm ERR! package.json Non-registry package missing package.json: squire-rte@github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621.
npm ERR! package.json npm can't find a package.json file in your current directory.

npm ERR! A complete log of this run can be found in:
npm ERR! C:\Users\mstacey\AppData\Roaming\npm-cache_logs\2019-03-11T10_10_15_631Z-debug.log

Expected Behavior
NPM install works without direct reference to github repos, and actually uses packaged components.
Github references don't work through corporate proxies
"squire-rte": "github:sohee-lee7/Squire#b1e0e1031fa18912d233c204cbe7c7fae4a42621" fails - whereas properly packaged packages can by cached in Proget or other tools.

This is a blocker for using this tool

**Comment by sohee-lee7** [comment]
@MstaceyMWAM I think your environment is blocked git protocol. 
(reference: https://stackoverflow.com/questions/4891527/git-protocol-blocked-by-company-how-can-i-get-around-that/10729634#10729634)
Try to config of git.
```
git config --global url."https://github".insteadOf github:
```

**Comment by MstaceyMWAM** [comment]
Hi

I chatted to our infra guys, and this is my (albeit limited) understanding of the why and how it's blocked:

They have deliberately blocked using github directly in that manner - their approach is that any build needs to happen based on a package they've synced down to our NPMCache. 
The reason is that we need to be able to rebuild any build at any time, regardless of external dependencies - so if Github went down / that specific repo/build in Github was corrupt / etc. we couldn't build. Whereas because we cache any npm package that is used in a build and our npm install uses only that cache, any build can work without any internet access. This is then the second issue even if I got your work around to work. Our build server doesn't have any external access and can only access packages in our cache.

 So in order for it to work, all dependencies need to be packages rather than direct references to a github

**Comment by sohee-lee7** [comment]
@MstaceyMWAM I have discussed this issue with my team members. We are not obligated to use all of the deputies distributed at NPM. NPM also supports git protocol for dependencies(https://docs.npmjs.com/files/package.json#git-urls-as-dependencies). So we don't need to apply for special cases like yours. 
Currently, we are distributing the `tui-editor-Editor-full.js` file containing all of the dependencies. If you use the file, you don't have to download all of the depends on your project. I recommend that you change your build system to use the full file.

**Comment by MstaceyMWAM** [comment]
Ahh OK - I think the full file can be made to work, I'll try that out. Thanks

**Comment by sohee-lee7** [comment]
Full file is supported in version 1.3.1 and toast-ui.vue-editor is compatible with all 1.3.x versions.
So I recommend using versions later than 1.3.1.

**Comment by gregroyal** [comment]
I'm having a similar issue. Why not contribute back your changes to the main repo? or create a new npm package for your fork

**Comment by sohee-lee7** [comment]
@gregroyal Squire has no response to my PR. It is assumed that Squire is not managed. We consider to publish forked Squrie or use other wysiwyg library. Therefore, please wait a moment. And since npm supports installing with the github repo, using github repo should not be a problem.

**Comment by gregroyal** [comment]
I am in the same situation as @MstaceyMWAM . Currently I have to repackage your library to be able to use it. Which right now I'm open to do it because it looks great! however its extra maintenance that isn't normal for any of our other libraries
