### ISSUE TITLE
Task clickable area

### ISSUE THREAD

**Issue by RomainFrancony** [nhnent/tui.editor#436]
## Version

1.3.2

## Test Environment

Chrome MacOS

## Current Behavior

Currently, in order to check a task, you need to click on an area of 18x18 pixels

https://github.com/nhnent/tui.editor/blob/51d11e2fa3fecf8b64750fb3f1150d0985c19445/src/js/wwTaskManager.js#L45

The downside of it is that when you customize the CSS of the checkbox (bigger checkbox on mobile for example), the area is still a 18x18 pixels square which is too small for mobile device.

## Expected Behavior

Use the height of the line in order to determine the height and width of the clickable area.

```js
const elementHeight = ev.target.offsetHeight;
const isOnTaskBox = ev.offsetX < elementHeight && ev.offsetY < elementHeight;
```
This way, we can customize the look of the checkbox and having a dynamic clickable area.

## Additional notes

The same problem happens in the viewer here:

https://github.com/nhnent/tui.editor/blob/3d5b51cc1f5e02860ed6d81173d35132f2d4930d/src/js/viewer.js#L89

**Comment by sohee-lee7** [comment]
@RomainFrancony It's a very good point. 👍  Thank you!!
I try to test the code suggested. That works well when change `line-height`.
The code will be reviewed by team members for inclusion in the next release. Or, if you have time, I would be very grateful if you could pull request yourself.

**Comment by RomainFrancony** [comment]
Hi I found one quirk with this solution, when the task is long and wrap on multiple lines, the height becomes bigger than the checkbox, so you can click on the whole left side of the task (the padding area).

An other solution would be to get the computed `line-height` : 
```js
const elementLineHeight = parseFloat(getComputedStyle(ev.target).lineHeight);
```

It seems to work on Chrome, Safari and Firefox but we should check ie and Edge

I will try to do the pull request this week.
