### ISSUE TITLE
Tag missing in codeblock after changed to wysiwyg mode

### ISSUE THREAD

**Issue by robertwang1987** [nhnent/tui.editor#448]
## Current Behavior: Tag missing in codeblock after changed to wysiwyg mode

I write code like below in md editor
![image](https://user-images.githubusercontent.com/11974127/54900701-3e4f5100-4f0f-11e9-89c5-384bda347f2f.png)

then switch to wysiwyg mode, I got this
![image](https://user-images.githubusercontent.com/11974127/54900724-56bf6b80-4f0f-11e9-8cf2-4d43cdfced68.png)

## Expected Behavior: Tag still shown

![image](https://user-images.githubusercontent.com/11974127/54900792-8a01fa80-4f0f-11e9-8745-83c8fba04f42.png)

I fork the code then change file
src/js/wwCodeBlockManager.js

from 
```js
$pre.html(resultText ? resultText : brString);
```
to
```js
$pre.html(resultText ? sanitizeHtmlCode(resultText) : brString);
```

hope it helped

**Comment by sohee-lee7** [comment]
@robertwang1987 This issue is ready to code review. After code review, it will be released v1.3.4.

**Comment by sohee-lee7** [comment]
#300

**Comment by sohee-lee7** [comment]
This issue is fixed so close it.
