### ISSUE TITLE
How to insert html where a cursor is located

### ISSUE THREAD

**Issue by LIFOsitory** [nhnent/tui.editor#453]
## Version

1.3.1

## Test Environment

웨일 브라우저(Windows 10)

## Expected Behavior

에디터에서 커서가 위치한 곳에 원하는 코드를 붙일 수 있는 API가 있나요?
Html 코드를 붙이고 싶습니다.

![image](https://user-images.githubusercontent.com/26114165/55135965-6c7f9b80-5170-11e9-822a-499c85c9d933.png)

**Comment by sohee-lee7** [comment]
@LIFOsitory Sorry for late reply. It is not possible to insert `HTML` but there is way to insert text.
If use `insertText` function, you could insert text in the cursor.
http://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#insertText

**Comment by LIFOsitory** [comment]
thanks for your comment!! 👍
