### ISSUE TITLE
Step missing from installation instructions

### ISSUE THREAD

**Issue by IckleChris** [nhnent/tui.editor#46]
## Version
1.0.1

## Test Environment
OSX Chrome 63.0.3239.132

## Current Behavior
The README isn't very clear as to what CSS files are required to be loaded for the component to function correctly. Additional to the two more obvious editor CSS files within `tui-editor`, the `codemirror/lib/codemirror.css` file was required. This could be more explicit in the installation instructions.

## Expected Behavior
Following the README installation instructions results in a fully functional component.

**Comment by CosmoMyzrailGorynych** [comment]
It also requires `/node_modules/highlight.js/styles/github.css`
