### ISSUE TITLE
Create a stand-alone version that can edit local markdown files

### ISSUE THREAD

**Issue by dessalines** [nhnent/tui.editor#50]
I'd love to see this as a stand-alone markdown editor too, like retext or typora, that can edit local markdown files.

**Comment by poVoq** [comment]
Syncing with Nextcloud would be awesome too, but maybe the easiest would be to integrate this into something like Joplin: https://github.com/laurent22/joplin

**Comment by cavo789** [comment]
Hello, just for info I've written a PHP application (to run on a localhost webserver) which is aimed to allow to edit markdown local files too. Currently based on another editor but I'm busy to change to tui.editor. I've to code a few things to finalize the migration (situation mid-june 2018). The application is called marknotes and is available as Open Source software on Github (see my profile).

**Comment by writepubapp** [comment]
Hello - 
You can use Write.Pub (which in turn uses TUI) to edit, save and version local markdown files. http://www.write.pub/download/

Cheers

**Comment by sohee-lee7** [comment]
This issue is old so close it. If you have any question, please make a new issue.
