### ISSUE TITLE
Use NPM for toMark dependency

### ISSUE THREAD

**Issue by Yaty** [nhnent/tui.editor#51]
Hi !

## Test Environment
Windows 7

## Current Behavior
I'm trying to `npm install --save tui-editor`.

I'm getting this error : 
```
npm ERR! Error while executing:
npm ERR! C:\Program Files\Git\cmd\git.EXE ls-remote -h -t ssh://git@github.com/nhnent/toMark.git
npm ERR!
npm ERR! FATAL ERROR: Network error: Connection refused
npm ERR! fatal: Could not read from remote repository.
npm ERR!
npm ERR! Please make sure you have the correct access rights
npm ERR! and the repository exists.
npm ERR!
npm ERR! exited with error code: 128
```

It seems to be a proxy issue but git and npm are already configured for my proxy.

I tried to run `git ls-remote`  independently : 
`git ls-remote -h -t ssh://git@github.com/nhnent/toMark.git` : same error
`git ls-remote -h -t https://github.com/nhnent/toMark.git` : the command never ends

Could you npm publish `toMark` and change package.json to use it that way ? I think that would solve my issue.

**Comment by kyuwoo-choi** [comment]
Yup. I have plan to publish toMark on npm.
I'll release patch for it soon.
Thanks

**Comment by Yaty** [comment]
And could you do the same with `plantuml-encoder` ? Thanks :)

**Comment by kyuwoo-choi** [comment]
ok. It seems https://github.com/markushedvall/plantuml-encoder/pull/8 issue has been solved.
I'll switch the plantuml-encoder too.

**Comment by kyuwoo-choi** [comment]
this will be shipped on 1.0.2

**Comment by kyuwoo-choi** [comment]
https://github.com/nhnent/tui.editor/releases

**Comment by kyuwoo-choi** [comment]
#134 needs to specify squire commit  https://github.com/neilj/Squire/commit/b0ac7d32d05dcaee2e7fbef3f2756868cbb83e84 

reopen this issue.
squire dependency will be npm version again when the squire issues are resolved.

**Comment by sohee-lee7** [comment]
Squire dependency was be npm version 1.9.0.
