### ISSUE TITLE
Add the ability to move toolbar & hide mode switch

### ISSUE THREAD

**Issue by michaelryancaputo** [nhnent/tui.editor#54]
Would really like to be able to position the toolbar to the bottom while retaining the menu popup functionality, like: table, right click on table etc.

Additionally would like to be able to remove the toolbar containing the markdown/wysiwyg toggle button.

I've been able to do these things with css but it seems to break some of the hover effects and causes some side effects.

**Comment by kyuwoo-choi** [comment]
That would be a worthwhile option.
But I have no time to handle this right this moment,
I'll tag this `help wanted` and consider on our roadmap.

**Comment by michaelryancaputo** [comment]
@kyuwoo-choi this is awesome!
Should I create a seperate card for "moving the toolbar"?

**Comment by kyuwoo-choi** [comment]
@michaelryancaputo Yea. That will help separating the issues.

**Comment by nicksp** [comment]
Are there any updates on the ability to change the position of the toolbar? cc @kyuwoo-choi
