### ISSUE TITLE
How do I enter media link?

### ISSUE THREAD

**Issue by ryujb** [nhnent/tui.editor#56]
## Current Behavior

```js


How do I enter media link?

동영상 링크를 입력할려면 어떻게 해야하나요?





```

**Comment by kyuwoo-choi** [comment]
Could you explain a bit more detail?
If you want to add a youtube video, there's a extension coming soon.

**Comment by kyuwoo-choi** [comment]
I'm closing it as there's no respond. If you have further question, feel free to reopen this.

**Comment by nam-co** [comment]
> Could you explain a bit more detail?
> If you want to add a youtube video, there's a extension coming soon.

Hy @kyuwoo-choi , I was wondering if the YouTube video extension was ever released? thanks
