### ISSUE TITLE
HTML mode

### ISSUE THREAD

**Issue by franfran** [nhnent/tui.editor#58]
Is there a way to have HTML mode?

Thx.

**Comment by kyuwoo-choi** [comment]
What do you mean by HTML mode?
Could you give me more explanation?

**Comment by franfran** [comment]
Hi,

"HTML mode" means to allow the editor to edit HTML code.

Thank you!

**Comment by kyuwoo-choi** [comment]
well I think we have no plan to add a HTML mode.
feel free to reopen it if you want to discuss about this.

**Comment by roryokane** [comment]
As a possible workaround, keep in mind that Markdown syntax allows HTML tags. You can already paste this HTML into the Markdown tab of TOAST UI Editor and it will render fine:

~~~html
<p>Here is <abbr title="Hypertext Markup Language">HTML</abbr>.</p>

<blockquote>
<p>You mean, you can have <b>formatting</b>?</p>
</blockquote>
~~~

However, if you switch to WYSIWYG mode and back again, the Markdown text is normalized:

~~~markdown
Here is <abbr title="Hypertext Markup Language">HTML</abbr>.

> You mean, you can have **formatting**?
~~~

So if you wanted to keep editing the text as HTML, that isn’t currently possible.
