### ISSUE TITLE
Being able to config extensions

### ISSUE THREAD

**Issue by Yaty** [nhnent/tui.editor#60]
Hi,
Is there a way to configure extensions ?
For example I would like to change the DEFAULT_RENDERER_URL to use mine.
https://github.com/nhnent/tui.editor/blob/377d148fd328ed3d54e6c9163a15b07264797632/src/js/extensions/uml.js#L10

**Comment by kyuwoo-choi** [comment]
hi @Yaty 

you can replace the url by give it in ext option.
see below example code

```js
$.('#editor').tuiEditor({
  ...
  exts: [{name: 'uml', rendererURL: 'http://your.custom.renderer/url'}]
  ...
});

**Comment by kyuwoo-choi** [comment]
I'm closing it. If you have more question about this, you can reopen.
