### ISSUE TITLE
It's a little uncomfortable to import dependencies

### ISSUE THREAD

**Issue by ParkSB** [nhnent/tui.editor#61]
## Version

v1.0.1
## Test Environment

OS: Windows 10 
Browsers: Google Chrome
## Current Behavior

The developers who want to use tui editor have to install lots of dependencies. Using package manager, they can install the dependencies easily, of course. 
However, I think it is a little uncomfortable to import the dependencies, like this.
```javascript
import 'markdown-it';
import 'toMark';
import 'codemirror';
import 'squire-rte';
import 'codemirror/lib/codemirror.css';
import 'tui-editor/dist/tui-editor.min.css';
import 'tui-editor/dist/tui-editor-contents.min.css';
import Editor from 'tui-editor';

let editor = new Editor({
  el: document.querySelector('#editor'),
  initialEditType: 'markdown',
  previewStyle: 'vertical',
  height: '300px'
});
```  
In addition, it is difficult to find the documents that explain about the dependencies. 
## Expected Behavior

I'd like to import all of dependencies at a time, but I don't know if that's possible. I'm sorry.
Also, I suggest updating [getting-started.md](docs/getting-started.md). It confuses beginners, because the codes on the document are too simple. I think it should explain about importing the dependencies.

**Comment by kyuwoo-choi** [comment]
Yea. I think I should consider to make a big one bundle or something.
