### ISSUE TITLE
Live Preview Switching Bug: Adding auto code tags.

### ISSUE THREAD

**Issue by aligoren** [nhnent/tui.editor#65]
**Version:** v 1.0.2

## Test Environment
Chrome: 63.0.3239.132, Windows 10

## Current Behavior
Hi. I used tui.editor to try it on this link: [https://nhnent.github.io/tui.editor/](https://nhnent.github.io/tui.editor/).

I added code tags like that:

```
 javascript
console.log(123); 
```

After I click WYSIWYG and then again I switched markdown tab tui.editor added extra *`* tags and deleted programming language that I declared. For example:

```
console.log(123);  
```

## Expected Behavior

It should stay without any data loss and when I navigate between tabs. I added this:

```
javascript
console.log(123); 
```

**I expected this:**

```

` ` ` javascript
console.log(123); 
` ` `
```

**Comment by kyuwoo-choi** [comment]
hey @aligoren thanks for reporting.

Adding a extra backtick is clearly a bug.

for the problem removing language declaration, could you give me the example more clearly?
I've tried with code below in markdown editor and switched mode to wysiwyg and back,
but I couldn't reproduce.
````
```javascript
console.log(123);
```
````

**Comment by aligoren** [comment]
Hi @kyuwoo-choi 

I tried my own project it worked truly. But I talked about this example: [https://nhnent.github.io/tui.editor/](https://nhnent.github.io/tui.editor/)

# Preview

![image](https://user-images.githubusercontent.com/4205423/35662661-68756790-072a-11e8-9622-578c486e3edf.png)

**Comment by kyuwoo-choi** [comment]
hey @aligoren 
I meant I want to know **original text** that causes **loosing language declaration**.

**Comment by aligoren** [comment]
@kyuwoo-choi I think I did not understand you. I'm sorry it's my fault. My English isn't very well.

If you are asking programming language, I tried for javascript, Python, Haskell, Ruby, C#, PHP all of them worked wrong after switching tabs like above image.

**Comment by kyuwoo-choi** [comment]
hehe @aligoren sorry it's my bad.
I'll try to fix this soon. 
good day! 😄

**Comment by aligoren** [comment]
@kyuwoo-choi Thanks a lot.
