### ISSUE TITLE
Disabling bold / italics with toolbar spawns more `*` if inner text is selected, not outer

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nhnent/tui.editor#71]
## Version
1.0.2

## Test Environment
Firefox Developer Edition (latest), nw.js (webkit latest).

## Current Behavior

1. Go to https://nhnent.github.io/tui.editor/ , find an editor with a code input.
2. Write `**bold**`
3. Double-click the `bold`. Note that only `bold` gets selected, not `**bold**`.
4. Click a Bold button on a toolbar.
5. Now you have `****bold****`.

These `__bolds__` are selected with underscores on double-clicking, and their formatting is removed correctly. But if exactly `bolds` are selected, it creates more symbols as well.

The same affects `*italics*`.

## Expected Behavior
You should get `bold` on step 5. Code editor should check for surrounding asterisks.

**Comment by sohee-lee7** [comment]
This issue is same #434 and that is fixed. So I close this issue.
