### ISSUE TITLE
Everything is based on 'px', is unscalable and doesn't respect the current color scheme. Preprocessors?

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nhnent/tui.editor#72]
## Version
1.0.2

## Test Environment
Firefox Developer Edition (latest), nw.js (webkit latest).

## Current Behavior

It is extremely hard to blend the editor with a real environment (I mean web page design), as it has inconsistent use of inline PNGs and SVGs, hard-coded 'px' units and all the other unfancy stuff. Honestly, the code smells. Like, stinks. It's a pity that such great FOSS project has ugly insides 😢 

There are no CSS variables or preprocessor codes to compile, and no way to style the editor except by manual editing of CSS files. I have a dark app with large typography and existing button & input styles, and I had to wipe out literally a half of all the CSS code of ToastUI editor. The other half is tweaked till now and is converted to stylus.

## Expected Behavior

There are several ways to solve this problem:

* use preprocessor with variables so users can config editor to their size, color, style requirements;
* create multiple themes, at least dark one (this will be much easier with preprocessors, though);
* allow to config colors and scale via js (hard to do and seems to be irrational 😐)

Besides that, I believe that no one should use `px` in 2018, but `rem`\`em` instead of that. You could also add source icons in SVG to the repo.

Please forgive me if I sound rude, I have a really tough time with ToastUI editor :/

**Comment by kyuwoo-choi** [comment]
@CosmoMyzrailGorynych 
any opinion to make it better is welcomed. yes. but you should be polite.
read https://github.com/nhnent/tui.editor/blob/master/CODE_OF_CONDUCT.md

**Comment by kyuwoo-choi** [comment]
btw. you know it's open source project.
discuss politely. encourage contributors and send me a PR if you can make it better.
It's 3years old project having tons of issues. I always need more hands you know that.

**Comment by twhite96** [comment]
I'm new to OSS. I may be able to take a look at the CSS here. @kyuwoo-choi would you like some help with this?

**Comment by kyuwoo-choi** [comment]
@twhite96 sure. thanks!

I'm a bit busy for v1.1.0 atm, I think I can look at it after that.
So, I can't give you a guide for now.
meanwhile just ask me anything, I'll try to respond.

**Comment by twhite96** [comment]
@kyuwoo-choi no problem. Looked at the `CONTRIBUTING.md` file but couldn't discern if I should make a new feature branch for this? If so I am going to hop on it.

**Comment by sohee-lee7** [comment]
This issue is old and we does not plan about this issue so close it.
