### ISSUE TITLE
WYSIWYG: Add 3+ horizontal lines, try to erase them, get +2 line breaks and same lines

### ISSUE THREAD

**Issue by CosmoMyzrailGorynych** [nhnent/tui.editor#73]
## Version
1.0.2

## Test Environment
Mozilla Firefox Developer Edition (latest), nw.js (webkit latest).

## Current Behavior

1. Open https://nhnent.github.io/tui.editor/
2. Find a WYSIWYG example
3. Insert 3 or more horizontal rows in, erm, in a row
4. Start erasing them with Backspace key. Notice as new paragraphs appear between the lines when you try to erase the second one.

It happens on any horizontal line number greater than two. Extra paragraphs appear exactly after trying to remove the second line at the bottom.

## Expected Behavior

No additional paragraphs or line breaks should appear.

**Comment by sohee-lee7** [comment]
@CosmoMyzrailGorynych Sorry for late reply. Horizontal line have some problem and all issue have same cause. So I create new issue of horizontal. We manage this issue in #402 with other issue.
