### ISSUE TITLE
Can write a detailed code for getHtml and getMarkdown

### ISSUE THREAD

**Issue by moyiblog** [nhnent/tui.editor#76]
Thank you for your contribution.

When it comes to write an issue, please, use the template below.
To use the template is mandatory for submit new issue and we won't reply the issue that without the template.

BUG ISSUE TEMPLATE 
## Version
Write the version of the tui-editor you are currently using. 

## Current Behavior

```js
// Write example code
```

**Comment by kyuwoo-choi** [comment]
ok. it's enough. you are now reported.
