### ISSUE TITLE
Override command behaviors

### ISSUE THREAD

**Issue by JulioC** [nhnent/tui.editor#77]
I'm using the editor on a Wiki platform and some commands need to be changed (eg strike-through is `<del>some text</del>`).

I understand the renderer will not parse these commands, but I still need to be able to change the default behavior for them.

How can I do that?

**Comment by kyuwoo-choi** [comment]
A Bad news is that we don't have that option for that.
A Good news is We have a plan to implement an option to customize toolbar soon. :)
No ETA yet. but It won't be so long.

**Comment by kyuwoo-choi** [comment]
it will be covered by #85
you can replace a button with a custom command.
