### ISSUE TITLE
events.change does not return changed value of the Editor

### ISSUE THREAD

**Issue by natterstefan** [nhnent/tui.editor#78]
## Version
- 1.0.2

## Test Environment
- Chrome (latest)
- MacOS (10.12.6)
- React Environment w/ Webpack

## Current Behavior

I implemented your javascript code, dependencies and got the editor to start with

```js
this.editor = new Editor({
        el: document.querySelector(selector),
        events: {
          change: this.onChange
        },
        height: style.height || '300px',
        initialValue: value
      })
```

The onChange looks like this (very basic):

```js
   onChange: (change) => { console.log('onChange triggered...', change) },
```

All I get now when I type in the Editor is something like:

```js
onChange triggered...,  {source: "wysiwyg"}
```

## Expected Behavior

I expect to get the new and updated value from the Editor. [Reading the docs](https://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#ToastUIEditor) did not really helped me as well. There is no further explanation of how the `change` event works (or I missed it).

Thank you for your help guys!

**Comment by kyuwoo-choi** [comment]
The Document must be improved. damn :(

You'll want to use [getValue()](https://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#getValue) for md string or [getHtml()](https://nhnent.github.io/tui.editor/api/latest/ToastUIEditor.html#getHtml) for html string in `onChange` event callback.

This is for purpose as calling the `getValue` and `getHtml` method is expansive.
You better avoid calling those methods every time the `change` event fires.
Call those when you sure that md/html is required.
