### ISSUE TITLE
Rendering bug in "WYSIWYG" mode for UML && Chart

### ISSUE THREAD

**Issue by mankash** [nhnent/tui.editor#81]
## Summary:
The[ example-00 demo](https://nhnent.github.io/tui.editor/api/latest/tutorial-example00-demo.html) on your github pages for UML & chart works properly in Markdown/preview mode, but switching to WYSIWYG mode causes a modification in the raw markdown, making it invalid!!

## Version:
0.14.5 (??)

## Environment: 
Chrome Browser on Mac OSX- Sierra, Ubuntu 16.04, Windows 7/10

## Expected Behavior:
Expect switching from Markdown to WYSIWYG to not cause issues.

**Comment by kyuwoo-choi** [comment]
Bah! It's a silly bug!
Thanks for reporting it.

**Comment by yihui** [comment]
When switching back from WYSIWYG to the markdown mode, two trailing spaces will be added to every single line in the code block, which will cause the same issue as #113 and the chart will fail to render.
