### ISSUE TITLE
Support "plantuml" LANG in fenced code (in addition to "uml")

### ISSUE THREAD

**Issue by cazeaux** [nhnent/tui.editor#87]
The UML extension expects the following fenced code:

````markdown
Text

```uml
@startuml
@enduml
```
````

Some editors like VS Code (see https://marketplace.visualstudio.com/items?itemName=jebbs.plantuml) support plantuml syntax highlighting (and preview) in markdown fenced code , but with the following form:

````markdown
Text

```plantuml
@startuml
@enduml
```
````

So there is a discrepancy between editor and renderer. Is it possible to make fenced code generate the plantuml schema for **uml** and **plantuml** languages ?

**Comment by kyuwoo-choi** [comment]
ok. let us find the other implementations first.
I don't want to add the languages everytime we find another one.
Could you help me find the others?

**Comment by cazeaux** [comment]
As far as I know, there is no other implementation beside **uml** and **plantuml** when it comes to describe a plantuml schema.

**Comment by kyuwoo-choi** [comment]
@cazeaux ok thanks.
I'll consider adding this to next minor release.
