### ISSUE TITLE
How to Add Button in the Toolbar

### ISSUE THREAD

**Issue by kishorethecoder** [nhnent/tui.editor#91]
## Version

1.03

## Test Environment

Windows 10
## Current Behavior

I started exploring Tui-editor which contains most of the required features. I want to add the button for Info,Warning and Error Box to the Toolbar. i got the reference for adding markdown-it-container to the TUIEditor with the piece of code from the link [#27](https://github.com/nhnent/tui.editor/issues/27).But, i  am not able to find a way to add the button and also  while looking at the document ,i saw that the ToolBar API has addButton method. However, i am not getting the toolbar instances in  editor.

## Expected Behavior

It would be great if you provide a way to get the access for toolbar to add button

**Comment by kyuwoo-choi** [comment]
covered in #85
