### ISSUE TITLE
How to save

### ISSUE THREAD

**Issue by mcules** [nhnent/tui.editor#93]
I want to save the content as a Part of a Form.
How can i do that?
With jquery i tried too without luck :(

**Comment by aarangara** [comment]
@mcules do you have sample code how you achieved this? I tried loading toast-ui editor for `textarea` in my form but no luck, works fine for `div`

**Comment by alcalyn** [comment]
Now, getValue seems not to work, you might need `editor.getMarkdown()` or `editor.getHTML()`. See https://nhn.github.io/tui.editor/latest/ToastUIEditorCore#getMarkdown
