### ISSUE TITLE
Problem with SSR, Add an option to not load anything until editor/viewer is actually instantiated

### ISSUE THREAD

**Issue by zlepper** [nhnent/tui.editor#95]
Sorry for not following your template, but this is not quite a bug. 

Some intro story:
We have an Angular application that we pre-render using Server Side Rendering. This doesn't work with the tui.editor, as it does some things on the global scope, immediately when it's loaded. We can easily just not call the constructor of tui on the server-side, and thus avoid any problems when the editor _actually_ is created, however the global things crashes on the serverside, as window doesn't exist, including most of the variables on window. 

So i would like to request that tui doesn't actually do anything before it has at least been requested to create one editor.

**Comment by kyuwoo-choi** [comment]
@zlepper sorry for the late.

Do you want to make it work with SSR right?
If so... I think your request is reasonable.
But, I haven't considered tui editor with the env yet. have no idea.

let me change the title of this issue, and hear the use cases and ideas.

Thanks.

**Comment by sohee-lee7** [comment]
This issue is old and we does not plan about this issue so I will close it.
