### ISSUE TITLE
Ability to create multiple editor using class

### ISSUE THREAD

**Issue by aarangara** [nhnent/tui.editor#99]
## Version
1.0.4

## Test Environment
Firefox Developer Edition 59.0b13 (64-bit), macOS High Seirra 10.13.3

## Current Behavior
I am trying to create multiple tui editors using class, but it only renders the editor for the first div.

## Expected Behavior
Is there any way I can create multiple tui editors on the same html page using class? Or will I have to use the ids for each div and then create tui editors from it?

**Comment by kyuwoo-choi** [comment]
sure. you can create multiple editors on a page.
and you should assign ids and initialize each editor according to the ids.

see gh-pages as an example
https://github.com/nhnent/tui.editor/blob/5ffad56dcab38c760d260b5ff5e35819367ccd07/index.html#L210
https://github.com/nhnent/tui.editor/blob/5ffad56dcab38c760d260b5ff5e35819367ccd07/index.html#L226-L232
https://github.com/nhnent/tui.editor/blob/5ffad56dcab38c760d260b5ff5e35819367ccd07/index.html#L214
https://github.com/nhnent/tui.editor/blob/5ffad56dcab38c760d260b5ff5e35819367ccd07/index.html#L234-L247
https://github.com/nhnent/tui.editor/blob/5ffad56dcab38c760d260b5ff5e35819367ccd07/index.html#L218
https://github.com/nhnent/tui.editor/blob/5ffad56dcab38c760d260b5ff5e35819367ccd07/index.html#L249-L266

em... I don't know what you mean by `using class`.
anyway, jquery plugin is just a wrapper around editor class.
https://github.com/nhnent/tui.editor/blob/b4b1bd1895b7521efdc2aaf079ab015c46fd8138/examples/example01-basic.html#L29-L34

**Comment by kyuwoo-choi** [comment]
I think I'm closing this issue.
feel free to open this issue again if you have a further question on this.

**Comment by aarangara** [comment]
By class, I meant using class selectors to load/render multiple toast ui editors.

Currently I have to do this : 
```
$(".editor").each(function () {
        $(this).tuiEditor({
            initialEditType: 'markdown',
            previewStyle: 'vertical',
            height: '300px'
        });
    });
```

Is it possible to allow something like below instead : 
```
$(".editor").tuiEditor({
            initialEditType: 'markdown',
            previewStyle: 'vertical',
            height: '300px'
});
```
